(function () {
    this.App = window.App || {};
    this.App.lang = {
        widgetName: 'AlvaKids widget',
        getTheRightSize: '取得尺寸建議',
        continueShopping: '繼續購物',
        helpCenter: '幫助中心',
        validation: {
            general: '請填妥標示的項目',
            username: {
                required: '請輸入用戶名稱',
                invalid: "必須由3-20個英文字母﹑數字﹑「-」 或「 _ 」組成",
            },
            name: {
                required: '請輸入用戶名稱',
                invalid: "必須由3-20個英文字母﹑數字﹑「-」 或「 _ 」組成",
            },
            password: {
                required: '請輸入密碼',
                invalid: '密碼必須由英文字母或數字組成',
                notMatch: "密碼並不正確",
            },
            new_password: {
                required: '請輸入新密碼',
                invalid: '密碼必須由英文字母或數字組成',
                notMatch: "密碼並不正確",
            },
            email: {
                required: '請輸入電郵地址',
                invalid: '無效電郵地址',
            },
            year: {
                required: '請輸入年份',
                invalid: '無效年份',
            },
            month: {
                required: '請輸入月份',
                invalid: '無效月份',
            },
            day: {
                required: '請輸入日期',
                invalid: '無效日期',
            },
            question: {
                required: '請輸入內容',
            },
            sex: {
                required: '請輸入性別',
            },
            gender: {
                required: '請輸入性別',
            },
            state: {
                required: '請輸入州份',
            },
            tandc: {
                required: '必須同意使用條款',
            },
            weight: {
                required: '請輸入體重',
            },
            height: {
                required: '請輸入身高',
            },
            child_name: {
                required: '請輸入名字',
            },
            ethnicity: {
                required: '請輸入種族',
            },
            date_of_birth: {
                required: '請輸入生日日期',
                invalid: '無效生日日期',
            }
        },
        navigation: {
            back: '返回',
            login: '登入',
            signup: '登記',
            getSize: '取得尺寸建議',
            continueShopping: '繼續購物',
            manageAccount: '帳戶管理',
            profiles: '檔案',
            logout: '登出',
            changePass: '更改密碼',
            resetMyPass: '重新設定密碼',
        },
        page: {
            about: '關於我們',
            howItWorks: '使用說明',
            faq: '常見問題',
            terms: '使用條款',
            privacy: '私隱聲明',
            help: '幫助',
        },
        about: {
            heading: 'AlvaKids是什麼？',
            para1: "AlvaKids的服務是為用戶提供尺寸建議以選擇合適的童裝。而我們的服務已發展至智能手機平台Android 及 iOs。",
            para2: '想了解更多？請到<a href="#page/faq">「幫助」</a>裡的常見問題或到訪我們的網頁<a href="http://www.alvakids.com/" target="_blank">www.AlvaKids.com</a>。',
            para3: "与AlvaKids享受購物樂趣吧！",
            version: "AlvaKids版本 v2.0",
        },
        register: {
            header: '登記',
            help: "完全免費，只需30秒即可完成登記。",
            userName: '用戶名稱',
            userNameOrEmail: '用戶名稱或電郵地址',
            gender: '性別',
            male: '男性',
            female: '女性',
            email: '電郵地址',
            password: '密碼',
            confirmPassword: '再次確定密碼',
            learnMore: '了解更多',
            tryFirst: '我想先試用',
            registerLater: '我想先試用後才登記',
            error: '登記失敗',
            optin: '同意接收AlvaKids的最新資訊',
            tandc: '同意Alva的<a href="http://alvakids.com/terms_of_use.html" target="_blank">使用條款</a>。',
            howAltImage: 'img/how-works-img.png',
            description: "AlvaKids 能幫助你的孩子找到最合適的童裝尺寸。使用AlvaKids 非常簡單，登記帳戶後，輸入孩子的基本尺寸來建立孩子檔案。之後AlvaKids 就能為你的孩子提供不同品牌最合適的童裝尺寸，就是這樣容易！隨著孩子成長，AlvaKids 亦會會根據每個孩子數據作調整，以確保現在甚至將來你都會得到最準確的建議。除此以外，當你登記了AlvaKids後，你還可以從 iTunes App Store 或 Google Play Store 免費下載 AlvaKids 的應用程式，只要登入你現有的帳戶，即可隨時隨地在你的手機上取得最合適的尺寸建議！",
        },
        settings: {
            editExplanation: '輸入你的個人資料以完成你的帳戶。必須輸入所有附有*的項目',
            username: '用戶名稱',
            firstName: '姓氏',
            lastName: '名字',
            email: '電郵地址',
            password: '密碼',
            gender: '性別',
            country: '居住國家',
            mobilePhone: '手機號碼',
            dateOfBirth: '生日',
            state: '州份',
            city: '居住城市',
        },
        changePassword: {
            explanation: '使用現有密碼以建立新密碼。如已經遺失了密碼，請在此輸入你的電郵地址，我們重新設定你的密碼及發送到你的電郵地址。',
            currentPassword: '現有密碼',
            newPassword: '新密碼',
            repeatNewPassword: '再次輸入新密碼',
            save: '儲存',
        },
        signup: {       // Signup after try it now
            saveKidProfile: "儲存檔案前，請填上所需資料。",
            reason: "登記你的名字和基本聯絡資料後，即可經由網上和手機應用程式上取得尺寸建議。",
        },
        login: {
            error: '錯誤！',
        },
        tryNow: {
            addProfile: "請填上孩子的基本尺寸以取得合適的尺寸建議。",
            getRecommendation: '取得尺寸建議',
        },
        miniWidget: {
            updateAndGetSize: "更新及取得尺寸建議",
            helpText: "請查看及更新孩子的資料。",
        },
        kidProfileAdd: {
            help: '建立孩子檔案以取得尺寸建議',
            clickToStart: '按此新增孩子檔案',
            fillIn: "填上你孩子的基本尺寸即可取得尺寸建議。",
            edit: "請於編輯完成後，按「儲存檔案」以確保所有更改已被保存。",
            uploadPic: '<strong>上載</strong>孩子的檔案頭像?',
            name: '孩子的名字',
            gender: '性別',
            skinny: '清瘦',
            regular: '適中',
            husky: '偏肥',
            longer: '較長',
            small: '較小',
            shorter: '較短',
            medium: '適中',
            big: '較大',
            male: '男孩',
            female: '女孩',
            leg: '半身比例',
            belly: '腹部大小',
            proportion: '體型',
            foot: '腳碼',
            inch: '英寸',
            cm: '厘米',
            kg: '公斤',
            inches: '英寸',
            ft: '英尺/英寸',
            lbs: '磅',
            stone: '英石',
            stonelbs: '英石/磅',
            chooseFt: '新增鞋號及腳碼',
            footSize: '腳碼',
            shoeSize: '鞋號',
            optional: '(可選)',
            save: '儲存檔案',
            wide: '腳較寬',
            ethnicity: '種族',
            ethnicities: [
                          { key: "African: Central", name: "非洲：中部" },
                          { key: "African: Eastern", name: "非洲：東部" },
                          { key: "African: Northern", name: "非洲：北部" },
                          { key: "African: Southern", name: "非洲：南部" },
                          { key: "African: Western", name: "非洲：西部" },
                          { key: "African-American", name: "非裔美國人" },
                          { key: "Arab/Middle eastern", name: "阿拉伯/中東" },
                          { key: "Asian: Chinese", name: "亞洲：中國" },
                          { key: "Asian: Indian/Pakistani", name: "亞洲：印度/巴基斯坦" },
                          { key: "Asian: Japanese", name: "亞洲：日本" },
                          { key: "Asian: Korean", name: "亞洲：韓國" },
                          { key: "Asian: South", name: "亞洲：南亞" },
                          { key: "Caribbean/Creole", name: "加勒比海/克裡奧爾人" },
                          { key: "Caucasian", name: "白種人" },
                          { key: "Hispanic/Latin", name: "西班牙/拉丁美洲人" },
                          { key: "Maori/Aboriginal", name: "毛利/土著人" },
                          { key: "Mediterranean", name: "地中海地區" },
                          { key: "Native American", name: "美洲印第安人" },
                          { key: "Other/Mixed", name: "其他/混血" }
            ],
        },
        kidProfile: {
            edit: '編輯',
            gender: '性別',
            height: '身高',
            weight: '體重',
            select: '選擇',
        },
        kidsProfiles: {
            intro: "我們會隨著孩子的成長自動調整孩子檔案的數據。請查看該檔案以確定其尺寸準確。",
            add: '按此新增孩子檔案',
            kidsImgAlt: '孩子的檔案',
            height: '身高',
            weight: '體重',
        },
        faq: {
            header: '常見問題',
            searchKeyword: '以關鍵字搜尋',
            faqs: [
                   {
                   question: "可否於店內購物時使用AlvaKids？",
                   answer: "可以！免費登記AlvaKids後可於網上和電話上使用。當你更新了帳戶或孩子檔案時，資料將會同步更新及顯示於電腦和電話上",
                   },{
                   question: "怎样编辑我孩子的个人档案？",
                   answer: "如需更加檔案內容，只需於孩子的檔案內按編輯即可，更可以更改你所有的檔案資料。",
                   },{
                   question: "为什么AlvaKids要知道我孩子的种族特征？",
                   answer: "AlvaKids个人档案会随着您孩子一起成长。我们的成长计算公式里里包含了不同种族的成长速率信息，这样保证您无论在现在还是将来都能得到准确的尺码建议。",
                   },{
                   question: "如何更加我的密碼？",
                   answer: "如需更改密碼，只須按右上角後點擊你的用戶名稱，即會看到「更改密碼」，按後將連接到更改密碼的畫面。",
                   },{
                   question: "我忘記了密碼應該怎麼辦？",
                   answer: "如忘記了密碼，請在主頁按登入，於下方即可看到「忘記密碼」。點擊後將會要求你填上你登記時的電郵地址，確定後你會收到附有新密碼的電郵供你再次登入。",
                   },{
                   question: "如何刪除孩子的檔案？",
                   answer: "刪除孩子的檔案只需在「孩子的檔案」按編輯後，在你想刪除的檔案旁按「刪除檔案」即可。",
                   },{
                   question: "怎樣取得AlvaKids的最新消息？",
                   answer: "如欲取得更多AlvaKids的訊息，請到我們<a href='https://www.facebook.com/AlvaKids' target='_blank'>Facebook</a>、關注Twitter <a href='https://twitter.com/AlvaKids' target='_blank'>@AlvaKids</a>或到<a href='http://www.alvakids.com/' target='_blank'>www.AlvaKids.com</a>查看我們更多資訊及訂閱我們的最新消息。",
                   },{
                   question: "如我有其他疑問該怎麼辦？",
                   answer: "如你有其他疑問的話，請告知你的疑問及電郵地址於右方，我們會儘管回應。",
                   },{
                   question: "我的孩子年齡較大該怎樣申請呢？",
                   answer: "AlvaKids是一款針對年齡小於16歲的孩子設計的應用。有些孩子成長速度較快，可能超過了兒童的尺碼範圍。這種情況下，我們沒辦法給您提供尺碼建議。這種情況下，我們建議您使用我們的<a href='http://www.alvafit.com'>AlvaFit</a>成人服裝尺碼推薦服務。",
                   },{
                   question: "Alvakids会用我的信息做什么用途？",
                   answer: "我們會小心處理你的個人資料，詳情請見<a href='http://www.alvakids.com/privacy_policy.html' target='_blank'>私隱聲明</a>及<a href='http://www.alvakids.com/terms_of_use.html' target='_blank'>使用條款</a>。",
                   }
            ]
        },
        newQuestion: {
            header: '找不到你想問的問題？',
            help: '請於下方輸入你的疑問及電郵地址，我們會盡快答覆您。',
            submitQuestion: '在此提交你的問題',
            yourEmail: '你的電郵地址',
            send: '傳送',
        },
        recommendation: {
            bestSize: '最適合孩子的尺寸是︰',
            error: '無法取得尺寸建議',
            noSizeAvailable: '未有合適尺寸',
            downloadAppReason: 'AlvaKids會根據孩子的成長調整每個孩子的檔案，以確保現在甚至將來你都會得到準確的建議。<br/>想在商店購物時取得合身的尺寸建議，請於 iTunes app store 或 Google Play免費下載我們 AlvaKids應用程式及登入你的帳戶即可馬上使用。',
            registerReason: '登記AlvaKids，我們將會保存你的資料以便提供該商品最準確的尺寸建議。AlvaKids亦會隨著孩子的成長調整數據，以確保現在甚至將來你都會得到準確的建議。',
            saveThisProfile: '儲存檔案即可在每個商品網頁上取得尺寸建議。',
        },
        countries: [
                    { key: "AD", name: "安道爾" },
                    { key: "AE", name: "阿聯酋" },
                    { key: "AF", name: "阿富汗" },
                    { key: "AG", name: "安提瓜和巴布達" },
                    { key: "AI", name: "安圭拉島" },
                    { key: "AL", name: "阿爾巴尼亞" },
                    { key: "AM", name: "亞美尼亞" },
                    { key: "AO", name: "安哥拉" },
                    { key: "AQ", name: "南極洲" },
                    { key: "AR", name: "阿根廷" },
                    { key: "AS", name: "美屬薩摩亞" },
                    { key: "AT", name: "奧地利" },
                    { key: "AU", name: "澳洲" },
                    { key: "AW", name: "阿魯巴" },
                    { key: "AX", name: "亞蘭群島" },
                    { key: "AZ", name: "阿塞拜疆" },
                    { key: "BA", name: "波黑" },
                    { key: "BB", name: "巴巴多斯" },
                    { key: "BD", name: "孟加拉" },
                    { key: "BE", name: "比利時" },
                    { key: "BF", name: "布基納法索" },
                    { key: "BG", name: "保加利亞" },
                    { key: "BH", name: "巴林" },
                    { key: "BI", name: "布隆迪" },
                    { key: "BJ", name: "貝寧" },
                    { key: "BL", name: "聖巴托洛繆島" },
                    { key: "BM", name: "百慕達" },
                    { key: "BN", name: "汶萊" },
                    { key: "BO", name: "玻利維亞" },
                    { key: "BQ", name: "荷蘭加勒比區" },
                    { key: "BR", name: "巴西" },
                    { key: "BS", name: "巴哈馬" },
                    { key: "BT", name: "不丹" },
                    { key: "BV", name: "鮑威特島" },
                    { key: "BW", name: "博茨瓦納" },
                    { key: "BY", name: "白俄羅斯" },
                    { key: "BZ", name: "伯利茲" },
                    { key: "CA", name: "加拿大" },
                    { key: "CC", name: "科科斯群島" },
                    { key: "CD", name: "民主剛果" },
                    { key: "CF", name: "中非" },
                    { key: "CG", name: "剛果" },
                    { key: "CH", name: "瑞士" },
                    { key: "CI", name: "科特迪瓦" },
                    { key: "CK", name: "庫克群島" },
                    { key: "CL", name: "智利" },
                    { key: "CM", name: "喀麥隆" },
                    { key: "CN", name: "大陸；" },
                    { key: "CO", name: "哥倫比亞" },
                    { key: "CR", name: "哥斯達黎加" },
                    { key: "CU", name: "古巴" },
                    { key: "CV", name: "佛得角" },
                    { key: "CW", name: "庫拉索" },
                    { key: "CX", name: "聖誕島" },
                    { key: "CY", name: "塞浦路斯" },
                    { key: "CZ", name: "捷克" },
                    { key: "DE", name: "德國" },
                    { key: "DJ", name: "吉布提" },
                    { key: "DK", name: "丹麥" },
                    { key: "DM", name: "多米尼克" },
                    { key: "DO", name: "多米尼加" },
                    { key: "DZ", name: "阿爾及利亞" },
                    { key: "EC", name: "厄瓜多爾" },
                    { key: "EE", name: "愛沙尼亞" },
                    { key: "EG", name: "埃及" },
                    { key: "EH", name: "西撒哈拉" },
                    { key: "ER", name: "厄立特里亞" },
                    { key: "ES", name: "西班牙" },
                    { key: "ET", name: "埃塞俄比亞" },
                    { key: "FI", name: "芬蘭" },
                    { key: "FJ", name: "斐濟" },
                    { key: "FK", name: "福克蘭群島（馬爾維納斯）" },
                    { key: "FM", name: "密克羅尼西亞" },
                    { key: "FO", name: "法羅群島" },
                    { key: "FR", name: "法國" },
                    { key: "GA", name: "加蓬" },
                    { key: "GB", name: "英國" },
                    { key: "GD", name: "格林納達" },
                    { key: "GE", name: "格魯吉亞" },
                    { key: "GF", name: "法屬圭亞那" },
                    { key: "GG", name: "根西島" },
                    { key: "GH", name: "加納" },
                    { key: "GI", name: "直布羅陀" },
                    { key: "GL", name: "格陵蘭" },
                    { key: "GM", name: "岡比亞" },
                    { key: "GN", name: "幾內亞" },
                    { key: "GP", name: "瓜德魯普島" },
                    { key: "GQ", name: "赤道幾內亞" },
                    { key: "GR", name: "希臘" },
                    { key: "GS", name: "南喬治亞島與南桑威奇群島" },
                    { key: "GT", name: "危地馬拉" },
                    { key: "GU", name: "關島" },
                    { key: "GW", name: "幾內亞比紹" },
                    { key: "GY", name: "圭亞那" },
                    { key: "HK", name: "香港" },
                    { key: "HM", name: "赫德島和麥克唐納群島" },
                    { key: "HN", name: "宏都拉斯" },
                    { key: "HR", name: "克羅地亞" },
                    { key: "HT", name: "海地" },
                    { key: "HU", name: "匈牙利" },
                    { key: "ID", name: "印尼" },
                    { key: "IE", name: "愛爾蘭" },
                    { key: "IL", name: "以色列" },
                    { key: "IM", name: "萌島" },
                    { key: "IN", name: "印度" },
                    { key: "IO", name: "英屬印度洋地區" },
                    { key: "IQ", name: "伊拉克" },
                    { key: "IR", name: "伊朗" },
                    { key: "IS", name: "冰島" },
                    { key: "IT", name: "意大利" },
                    { key: "JE", name: "澤西" },
                    { key: "JM", name: "牙買加" },
                    { key: "JO", name: "約旦" },
                    { key: "JP", name: "日本" },
                    { key: "KE", name: "肯尼亞" },
                    { key: "KG", name: "吉爾吉斯" },
                    { key: "KH", name: "柬埔寨" },
                    { key: "KI", name: "基里巴斯" },
                    { key: "KM", name: "科摩羅" },
                    { key: "KN", name: "聖基茨和尼維斯" },
                    { key: "KP", name: "朝鲜；" },
                    { key: "KR", name: "韓國；" },
                    { key: "KW", name: "科威特" },
                    { key: "KY", name: "開曼群島" },
                    { key: "KZ", name: "哈薩克" },
                    { key: "LA", name: "老撾" },
                    { key: "LB", name: "黎巴嫩" },
                    { key: "LC", name: "聖盧西亞" },
                    { key: "LI", name: "列支敦士登" },
                    { key: "LK", name: "斯里蘭卡" },
                    { key: "LR", name: "利比里亞" },
                    { key: "LS", name: "萊索托" },
                    { key: "LT", name: "立陶宛" },
                    { key: "LU", name: "盧森堡" },
                    { key: "LV", name: "拉脫維亞" },
                    { key: "LY", name: "利比亞" },
                    { key: "MA", name: "摩洛哥" },
                    { key: "MC", name: "摩納哥" },
                    { key: "MD", name: "摩爾多瓦" },
                    { key: "ME", name: "黑山" },
                    { key: "MF", name: "法屬聖馬丁" },
                    { key: "MG", name: "馬達加斯加" },
                    { key: "MH", name: "馬紹爾群島" },
                    { key: "MK", name: "馬其頓" },
                    { key: "ML", name: "馬里" },
                    { key: "MM", name: "緬甸" },
                    { key: "MN", name: "蒙古國" },
                    { key: "MO", name: "澳門" },
                    { key: "MP", name: "北馬里亞納群島" },
                    { key: "MQ", name: "馬提尼克" },
                    { key: "MR", name: "毛里塔尼亞" },
                    { key: "MS", name: "蒙塞拉特島" },
                    { key: "MT", name: "馬爾他" },
                    { key: "MU", name: "毛里求斯" },
                    { key: "MV", name: "馬爾代夫" },
                    { key: "MW", name: "馬拉維" },
                    { key: "MX", name: "墨西哥" },
                    { key: "MY", name: "馬來西亞" },
                    { key: "MZ", name: "莫桑比克" },
                    { key: "NA", name: "納米比亞" },
                    { key: "NC", name: "新喀里多尼亞" },
                    { key: "NE", name: "尼日爾" },
                    { key: "NF", name: "諾福克島" },
                    { key: "NG", name: "尼日利亞" },
                    { key: "NI", name: "尼加拉瓜" },
                    { key: "NL", name: "荷蘭" },
                    { key: "NO", name: "挪威" },
                    { key: "NP", name: "尼泊爾" },
                    { key: "NR", name: "瑙魯" },
                    { key: "NU", name: "紐埃" },
                    { key: "NZ", name: "新西蘭" },
                    { key: "OM", name: "阿曼" },
                    { key: "PA", name: "巴拿馬" },
                    { key: "PE", name: "秘魯" },
                    { key: "PF", name: "法屬波利尼西亞" },
                    { key: "PG", name: "巴布亞新幾內亞" },
                    { key: "PH", name: "菲律賓" },
                    { key: "PK", name: "巴基斯坦" },
                    { key: "PL", name: "波蘭" },
                    { key: "PM", name: "聖皮埃爾島和密克隆島" },
                    { key: "PN", name: "皮特凱恩群島" },
                    { key: "PR", name: "波多黎各" },
                    { key: "PS", name: "巴勒斯坦" },
                    { key: "PT", name: "葡萄牙" },
                    { key: "PW", name: "帕勞；帛琉" },
                    { key: "PY", name: "巴拉圭" },
                    { key: "QA", name: "卡塔爾" },
                    { key: "RE", name: "留尼汪" },
                    { key: "RO", name: "羅馬尼亞" },
                    { key: "RS", name: "塞爾維亞" },
                    { key: "RU", name: "俄羅斯" },
                    { key: "RW", name: "盧旺達" },
                    { key: "SA", name: "沙特阿拉伯" },
                    { key: "SB", name: "所羅門群島" },
                    { key: "SC", name: "塞舌爾" },
                    { key: "SD", name: "蘇丹" },
                    { key: "SE", name: "瑞典" },
                    { key: "SG", name: "新加坡；" },
                    { key: "SH", name: "聖赫勒拿" },
                    { key: "SI", name: "斯洛文尼亞" },
                    { key: "SJ", name: "斯瓦爾巴特群島" },
                    { key: "SK", name: "斯洛伐克" },
                    { key: "SL", name: "塞拉利昂" },
                    { key: "SM", name: "聖馬力諾" },
                    { key: "SN", name: "塞內加爾" },
                    { key: "SO", name: "索馬里" },
                    { key: "SR", name: "蘇里南" },
                    { key: "SS", name: "南蘇丹" },
                    { key: "ST", name: "聖多美及普林西比" },
                    { key: "SV", name: "薩爾瓦多" },
                    { key: "SX", name: "荷屬聖馬丁" },
                    { key: "SY", name: "敘利亞" },
                    { key: "SZ", name: "斯威士蘭" },
                    { key: "TC", name: "特克斯和凱科斯群島" },
                    { key: "TD", name: "乍得" },
                    { key: "TF", name: "法屬南部地區" },
                    { key: "TG", name: "多哥" },
                    { key: "TH", name: "泰國" },
                    { key: "TJ", name: "塔吉克" },
                    { key: "TK", name: "托克勞群島" },
                    { key: "TL", name: "東帝汶" },
                    { key: "TM", name: "土庫曼" },
                    { key: "TN", name: "突尼斯" },
                    { key: "TO", name: "湯加" },
                    { key: "TR", name: "土耳其" },
                    { key: "TT", name: "千里達和多巴哥" },
                    { key: "TV", name: "圖瓦盧" },
                    { key: "TW", name: "台湾；" },
                    { key: "TZ", name: "坦桑尼亞" },
                    { key: "UA", name: "烏克蘭" },
                    { key: "UG", name: "烏干達" },
                    { key: "UM", name: "美國海外小島" },
                    { key: "US", name: "美國" },
                    { key: "UY", name: "烏拉圭" },
                    { key: "UZ", name: "烏茲別克" },
                    { key: "VA", name: "梵蒂岡" },
                    { key: "VC", name: "聖文森特和格林納丁斯" },
                    { key: "VE", name: "委內瑞拉" },
                    { key: "VG", name: "英屬處女群島" },
                    { key: "VI", name: "美屬處女群島" },
                    { key: "VN", name: "越南" },
                    { key: "VU", name: "瓦努阿圖" },
                    { key: "WF", name: "瓦利斯群島和富圖納群島" },
                    { key: "WS", name: "薩摩亞" },
                    { key: "YE", name: "也門" },
                    { key: "YT", name: "馬約特" },
                    { key: "ZA", name: "南非" },
                    { key: "ZM", name: "贊比亞" },
                    { key: "ZW", name: "津巴布韋" }
        ],
        states: {
            US: [
            ]
        }
    }
}).call(this);
