(function () {
    this.App = window.App || {};
    this.App.lang = {
        widgetName: 'AlvaKids widget',
        getTheRightSize: '获得正确的尺码建议：',
        continueShopping: '继续购物',
        helpCenter: '帮助中心',
        validation: {
            general: '请修改提示部分的内容',
            username: {
                required: '请输入用户名称',
                invalid: "必须由3-20个英文字母、数字、「 - 」或「 _ 」组成",
            },
            name: {
                required: '请输入用户名称',
                invalid: "必须由3-20个英文字母、数字、「 - 」或「 _ 」组成",
            },
            password: {
                required: '请输入密码',
                invalid: '密码必须由英文字母或数字组成',
                notMatch: "密码不正确",
            },
            new_password: {
                required: '请输入新密码',
                invalid: '密码必须由英文字母或数字组成',
                notMatch: "密码不正确",
            },
            email: {
                required: '请输入电邮地址',
                invalid: '无效电邮地址',
            },
            year: {
                required: '请输入年份',
                invalid: '无效年份',
            },
            month: {
                required: '请输入月份',
                invalid: '无效月份',
            },
            day: {
                required: '请输入日期',
                invalid: '无效日期',
            },
            question: {
                required: '请输入内容',
            },
            sex: {
                required: '请输入性别',
            },
            gender: {
                required: '请输入性别',
            },
            state: {
                required: '请输入州份',
            },
            tandc: {
                required: '必须同意使用条款',
            },
            weight: {
                required: '请输入体重',
            },
            height: {
                required: '请输入身高',
            },
            child_name: {
                required: '请输入名字',
            },
            ethnicity: {
                required: '请输入种族',
            },
            date_of_birth: {
                required: '请输入生日日期',
                invalid: '无效生日日期',
            }
        },
        navigation: {
            back: '返回',
            login: '登录',
            signup: '注册',
            getSize: '获得尺码建议',
            continueShopping: '继续购物',
            manageAccount: '帳戶管理',
            profiles: '个人档案',
            logout: '登出',
            changePass: '修改密码',
            resetMyPass: '重置密码',
        },
        page: {
            about: '关于我们',
            howItWorks: '使用预览',
            faq: '常见问题',
            terms: '使用条款',
            privacy: '隐私声明',
            help: '帮助',
        },
        about: {
            heading: 'Alvakids是什么？',
            para1: "Alvakids是一项为您的孩子提供服装尺码建议的服务。我们的服务可以在网站上使用，也可以通过Android和iOS的手机应用使用。",
            para2: '想知道更多吗？请前往<a href="#page/faq">帮助页面</a>，参考我们的FAQ，或访问我们的网站<a href="http://www.alvakids.com/" target="_blank">www.Alvakids.com</a>。',
            para3: "和Alvakids一起来购物吧!",
            version: "Alvakids版本 v2.0",
        },
        register: {
            header: '注册',
            help: "完全免费，只需30秒",
            userName: '用户名',
            userNameOrEmail: '用户名或电子邮箱',
            gender: '性别',
            male: '男性',
            female: '女性',
            email: '电子邮箱',
            password: '密码',
            confirmPassword: '再次确认密码',
            learnMore: '知道更多',
            tryFirst: '先试用一下',
            registerLater: '先试用，再注册',
            error: '注册失败',
            optin: '我希望收到AlvaKids的资讯',
            tandc: '我同意Alva的<a href="http://alvakids.com/terms_of_use.html" target="_blank">使用条款</a>。',
            howAltImage: 'img/how-works-img.png',
            description: "AlvaKids 帮助您找到适合您孩子的衣服尺码。 使用非常简单；注册一个帐户，然后创建一个您孩子的个人档案，输入他（她）的基本身型信息。 AlvaKids经过计算，便会得出最适合您孩子的各个品牌衣服尺码推荐。就是这么简单。 随着时间的推移，AlvaKids会让您孩子的个人档案与他（她）一起成长，确保您获得最准确的尺码建议，无论现在还是将来。 还不仅仅止于此哦，当您注册AlvaKids账户后，只要从iTunes App Store或Google Play下载到alvakids 应用程序，就可以在商场购物时，方便地获得我们的服装尺码建议了。 即刻下载免费的应用程序，使用您在网站上注册的账户登录，就可以随时随地用手机收到我们给您量体裁身的尺码建议啦！",
        },
        settings: {
            editExplanation: '填入空缺信息，完成注册步骤。 带星号*的内容为必填内容。',
            username: '用户名',
            firstName: '名',
            lastName: '姓',
            email: '电子邮箱',
            password: '密码',
            gender: '性别',
            country: '居住国家',
            mobilePhone: '手机号码',
            dateOfBirth: '生日',
            state: '州',
            city: '居住城市',
        },
        changePassword: {
            explanation: '输入您当前的密码，用来添加新密码。如果您丢失了密码，请提交您的电子邮箱，我们会重新设置您的密码，将新密码发送到您的邮箱里。',
            currentPassword: '现有密码',
            newPassword: '新密码',
            repeatNewPassword: '再次输入新密码',
            save: '保存',
        },
        signup: {       // Signup after try it now
            saveKidProfile: "您需填入空缺部分的信息，用来保存您孩子的个人档案。个人档案将会被保存在您的帐户下。",
            reason: "您需用您自己的信息注册一个帐户，方可储存您孩子的个人档案。填入您的姓名和基本联系信息注册成功后，你便可以在网页上和手机应用里，得到我们向给您的尺码建议了。",
        },
        login: {
            error: '错误！',
        },
        tryNow: {
            addProfile: "请填入您孩子的基本身型信息，获得我们的尺码推荐。",
            getRecommendation: '获得尺码建议',
        },
        miniWidget: {
            updateAndGetSize: "更新及取得尺码建议",
            helpText: "请查看及更新孩子的资料。",
        },
        kidProfileAdd: {
            help: '为您的孩子创建一个档案，用来获得尺码推荐。',
            clickToStart: '点击这里，开始添加孩子档案',
            fillIn: "填上你孩子的基本信息和身型特征即可取得尺码建议。",
            edit: "编辑后，点击“保存档案”，确保所做的修改已保存。",
            uploadPic: '<strong>上传</strong>一张您孩子的照片?',
            name: '孩子的名字',
            gender: '性别',
            skinny: '偏瘦',
            regular: '适中',
            husky: '略胖',
            longer: '下身较长',
            small: '偏小',
            shorter: '下身较短',
            medium: '中等',
            big: '偏大',
            male: '男孩',
            female: '女孩',
            leg: '半身比例',
            belly: '腹部大小',
            proportion: '体型',
            foot: '脚码',
            inch: '英寸',
            cm: '厘米',
            kg: '公斤',
            inches: '英寸',
            ft: '英尺/英寸',
            lbs: '磅',
            stone: '英石',
            stonelbs: '英石/磅',
            chooseFt: '输入鞋码或脚码',
            footSize: '脚码',
            shoeSize: '鞋码',
            optional: '(可选）',
            save: '保存档案',
            wide: '宽脚型',
            ethnicity: '种族',
            ethnicities: [
                          { key: "African: Central", name: "非洲：中部" },
                          { key: "African: Eastern", name: "非洲：东部" },
                          { key: "African: Northern", name: "非洲：北部" },
                          { key: "African: Southern", name: "非洲：南部" },
                          { key: "African: Western", name: "非洲：西部" },
                          { key: "African-American", name: "非裔美国人" },
                          { key: "Arab/Middle eastern", name: "阿拉伯/中东" },
                          { key: "Asian: Chinese", name: "亚洲：中国" },
                          { key: "Asian: Indian/Pakistani", name: "亚洲：印度/巴基斯坦" },
                          { key: "Asian: Japanese", name: "亚洲：日本" },
                          { key: "Asian: Korean", name: "亚洲：韩国" },
                          { key: "Asian: South", name: "亚洲：南亚" },
                          { key: "Caribbean/Creole", name: "加勒比海/克里奥尔人" },
                          { key: "Caucasian", name: "白种人" },
                          { key: "Hispanic/Latin", name: "西班牙/拉丁美洲人" },
                          { key: "Maori/Aboriginal", name: "毛利/土著人" },
                          { key: "Mediterranean", name: "地中海地区" },
                          { key: "Native American", name: "美洲印第安人" },
                          { key: "Other/Mixed", name: "其他/混血" },

            ],
        },
        kidProfile: {
            edit: '编辑',
            gender: '性别',
            height: '身高',
            weight: '体重',
            select: '选择择',
        },
        kidsProfiles: {
            intro: "我们的系统会让您孩子档案里的个人信息和他（她）一同成长。请查看个人档案，确认更新的信息和您孩子当前的真实情况相符合。",
            add: '按此处添加孩子档案',
            kidsImgAlt: '孩子的档案',
            height: '身高',
            weight: '体重',
        },
        faq: {
            header: '常见问题',
            searchKeyword: '关键词搜索',
            faqs: [
                   {
                   question: "我可以在商店购物时使用AlvaKids吗？",
                   answer: "可以！注册alvakids后，您就可以在网站上或手机应用里使用AlvaKids啦！当您更新了帐户或孩子档案，您在网站上和手机应用上的信息也会在同一时间自动更新。",
                   },{
                   question: "如何編輯我孩子的個人檔案？",
                   answer: "如果您想要修改个人档案的内容，只需在孩子的【档案概览】页面点击编辑即可，您就可以对所有已保存的信息进行修改了。",
                   },{
                   question: "為什麼要詢問我孩子的種族？",
                   answer: "當你的孩子成長，AlvaKids的資料亦會根據不同國家的兒童數據作調整，以確保現在甚至將來你都會得到準確的建議。",
                   },{
                   question: "如何修改我的密码？",
                   answer: "如需修改密码，在右上角的菜单区域，您会看到您的用户名。只需点击用户名，就能在展开的菜单找到“修改密码”的选项了。点击它，您便会被转到修改密码的页面。",
                   },{
                   question: "我忘记密码了，怎么办？",
                   answer: "如果您丢失了密码，请在主页面点击登录键，在登录区下方您会看到”忘记密码？”四个字。点击它，系统便会要求您输入与这个账户相关联的邮箱地址。提交您的邮箱地址后，我们会给您发送一封包含新密码的邮件。",
                   },{
                   question: "如何删除孩子的档案？",
                   answer: "如果您想要删除孩子的个人档案，请点击【档案概览】页面上的编辑按键。在每个孩子的个人档案里，都会有一个“删除档案”按键。点击，即可删除。",
                   },{
                   question: "哪里可以取得AlvaKids的最新消息？",
                   answer: "想要知道更多关于AlvaKids的信息和订阅新资讯的服务，请到我们的<a href='https://www.facebook.com/AlvaKids' target='_blank'>Facebook</a> 页面，或关注Twitter <a href='https://twitter.com/AlvaKids' target='_blank'>@AlvaKids</a>，及我们的官方网站target='_blank'>@AlvaKids</a>) ou jeter un oeil à <a href='http://www.alvakids.com/' target='_blank'>www.AlvaKids.com</a> 。",
                   },{
                   question: "我的问题在这里找不到？",
                   answer: "如果您的问题在这里找不到，请您的问题和您的电子邮箱地址发送给我们，我们会尽快答复您。",
                   },{
                   question: "我孩子的身形超过了这个应用的范围？",
                   answer: "AlvaKids是一款针对年龄小于16岁的孩子设计的应用。有些孩子成长速度较快，可能超过了儿童的尺码范围。这种情况下，我们没办法给您提供尺码建议。这种情况下，我们建议您使用我们的<a href='http://www.alvafit.com'>AlvaFit</a>成人服装尺码推荐服务。",
                   },{
                   question: "AlvaKids會將我的資料作甚麼用途呢？",
                   answer: "我们会小心的保管您的信息，详情请参考<a href='http://www.alvakids.com/privacy_policy.html' target='_blank'>隐私声明</a>和<a href='http://www.alvakids.com/terms_of_use.html' target='_blank'>使用条款</a>。",
                   }
            ]
        },
        newQuestion: {
            header: '找不到您想问的问题？',
            help: '即刻告诉我们！提交您的问题和电子邮箱地址，我们会尽快答复您。',
            submitQuestion: '在这里提交新的品牌',
            yourEmail: '您的电子邮箱',
            send: '发送问题',
        },
        recommendation: {
            bestSize: '适合您孩子的最佳尺码是：',
            error: '无法取得尺码建议',
            noSizeAvailable: '没有合适的尺码',
            downloadAppReason: 'AlvaKids会根据孩子的成长调整每个孩子的档案，以确保现在以及将来您都能得到准确的建议。<BR/>如果您想在商店购物时也能取得合身的尺寸建议，请于iTunes的应用程序商店或Good Play免费下载我们的AlvaKids应用，用您已有的AlvaKids帐户登录即可马上使用。',
            registerReason: '注册AlvaKids， 我们将会为您保存您孩子的个人档案，方便为您提供不同服装单品的尺码推荐。AlvaKids个人档案会随着您孩子一起成长，确保您在将来也能获得正确的尺码建议。',
            saveThisProfile: '保存档案，获得网站上更多衣服的尺码建议。',
        },
        countries: [
                    { key: "AD", name: "安道尔" },
                    { key: "AE", name: "阿联酋" },
                    { key: "AF", name: "阿富汗" },
                    { key: "AG", name: "安提瓜和巴布达" },
                    { key: "AI", name: "安圭拉" },
                    { key: "AL", name: "阿尔巴尼亚" },
                    { key: "AM", name: "亚美尼亚" },
                    { key: "AO", name: "安哥拉" },
                    { key: "AQ", name: "南极洲" },
                    { key: "AR", name: "阿根廷" },
                    { key: "AS", name: "美属萨摩亚" },
                    { key: "AT", name: "奥地利" },
                    { key: "AU", name: "澳大利亚" },
                    { key: "AW", name: "阿鲁巴" },
                    { key: "AX", name: "奥兰群岛" },
                    { key: "AZ", name: "阿塞拜疆" },
                    { key: "BA", name: "波黑" },
                    { key: "BB", name: "巴巴多斯" },
                    { key: "BD", name: "孟加拉" },
                    { key: "BE", name: "比利时" },
                    { key: "BF", name: "布基纳法索" },
                    { key: "BG", name: "保加利亚" },
                    { key: "BH", name: "巴林" },
                    { key: "BI", name: "布隆迪" },
                    { key: "BJ", name: "贝宁" },
                    { key: "BL", name: "圣巴泰勒米岛" },
                    { key: "BM", name: "百慕大" },
                    { key: "BN", name: "文莱" },
                    { key: "BO", name: "玻利维亚" },
                    { key: "BQ", name: "荷兰加勒比区" },
                    { key: "BR", name: "巴西" },
                    { key: "BS", name: "巴哈马" },
                    { key: "BT", name: "不丹" },
                    { key: "BV", name: "布韦岛" },
                    { key: "BW", name: "博茨瓦纳" },
                    { key: "BY", name: "白俄罗斯" },
                    { key: "BZ", name: "伯利兹" },
                    { key: "CA", name: "加拿大" },
                    { key: "CC", name: "科科斯群岛" },
                    { key: "CD", name: "刚果（金）" },
                    { key: "CF", name: "中非" },
                    { key: "CG", name: "刚果（布）" },
                    { key: "CH", name: "瑞士" },
                    { key: "CI", name: "科特迪瓦" },
                    { key: "CK", name: "库克群岛" },
                    { key: "CL", name: "智利" },
                    { key: "CM", name: "喀麦隆" },
                    { key: "CN", name: "中国；" },
                    { key: "CO", name: "哥伦比亚" },
                    { key: "CR", name: "哥斯达黎加" },
                    { key: "CU", name: "古巴" },
                    { key: "CV", name: "佛得角" },
                    { key: "CW", name: "库拉索" },
                    { key: "CX", name: "圣诞岛" },
                    { key: "CY", name: "塞浦路斯" },
                    { key: "CZ", name: "捷克" },
                    { key: "DE", name: "德国" },
                    { key: "DJ", name: "吉布提" },
                    { key: "DK", name: "丹麦" },
                    { key: "DM", name: "多米尼克" },
                    { key: "DO", name: "多米尼加" },
                    { key: "DZ", name: "阿尔及利亚" },
                    { key: "EC", name: "厄瓜多尔" },
                    { key: "EE", name: "爱沙尼亚" },
                    { key: "EG", name: "埃及" },
                    { key: "EH", name: "西撒哈拉" },
                    { key: "ER", name: "厄立特里亚" },
                    { key: "ES", name: "西班牙" },
                    { key: "ET", name: "埃塞俄比亚" },
                    { key: "FI", name: "芬兰" },
                    { key: "FJ", name: "斐济群岛" },
                    { key: "FK", name: "马尔维纳斯群岛（福克兰）" },
                    { key: "FM", name: "密克罗尼西亚联邦" },
                    { key: "FO", name: "法罗群岛" },
                    { key: "FR", name: "法国" },
                    { key: "GA", name: "加蓬" },
                    { key: "GB", name: "英国" },
                    { key: "GD", name: "格林纳达" },
                    { key: "GE", name: "格鲁吉亚" },
                    { key: "GF", name: "法属圭亚那" },
                    { key: "GG", name: "根西岛" },
                    { key: "GH", name: "加纳" },
                    { key: "GI", name: "直布罗陀" },
                    { key: "GL", name: "格陵兰" },
                    { key: "GM", name: "冈比亚" },
                    { key: "GN", name: "几内亚" },
                    { key: "GP", name: "瓜德罗普" },
                    { key: "GQ", name: "赤道几内亚" },
                    { key: "GR", name: "希腊" },
                    { key: "GS", name: "南乔治亚岛和南桑威奇群岛" },
                    { key: "GT", name: "危地马拉" },
                    { key: "GU", name: "关岛" },
                    { key: "GW", name: "几内亚比绍" },
                    { key: "GY", name: "圭亚那" },
                    { key: "HK", name: "香港" },
                    { key: "HM", name: "赫德岛和麦克唐纳群岛" },
                    { key: "HN", name: "洪都拉斯" },
                    { key: "HR", name: "克罗地亚" },
                    { key: "HT", name: "海地" },
                    { key: "HU", name: "匈牙利" },
                    { key: "ID", name: "印尼" },
                    { key: "IE", name: "爱尔兰" },
                    { key: "IL", name: "以色列" },
                    { key: "IM", name: "马恩岛" },
                    { key: "IN", name: "印度" },
                    { key: "IO", name: "英属印度洋领地" },
                    { key: "IQ", name: "伊拉克" },
                    { key: "IR", name: "伊朗" },
                    { key: "IS", name: "冰岛" },
                    { key: "IT", name: "意大利" },
                    { key: "JE", name: "泽西岛" },
                    { key: "JM", name: "牙买加" },
                    { key: "JO", name: "约旦" },
                    { key: "JP", name: "日本" },
                    { key: "KE", name: "肯尼亚" },
                    { key: "KG", name: "吉尔吉斯斯坦" },
                    { key: "KH", name: "柬埔寨" },
                    { key: "KI", name: "基里巴斯" },
                    { key: "KM", name: "科摩罗" },
                    { key: "KN", name: "圣基茨和尼维斯" },
                    { key: "KP", name: "朝鲜；" },
                    { key: "KR", name: "韩国；" },
                    { key: "KW", name: "科威特" },
                    { key: "KY", name: "开曼群岛" },
                    { key: "KZ", name: "哈萨克斯坦" },
                    { key: "LA", name: "老挝" },
                    { key: "LB", name: "黎巴嫩" },
                    { key: "LC", name: "圣卢西亚" },
                    { key: "LI", name: "列支敦士登" },
                    { key: "LK", name: "斯里兰卡" },
                    { key: "LR", name: "利比里亚" },
                    { key: "LS", name: "莱索托" },
                    { key: "LT", name: "立陶宛" },
                    { key: "LU", name: "卢森堡" },
                    { key: "LV", name: "拉脱维亚" },
                    { key: "LY", name: "利比亚" },
                    { key: "MA", name: "摩洛哥" },
                    { key: "MC", name: "摩纳哥" },
                    { key: "MD", name: "摩尔多瓦" },
                    { key: "ME", name: "黑山" },
                    { key: "MF", name: "法属圣马丁" },
                    { key: "MG", name: "马达加斯加" },
                    { key: "MH", name: "马绍尔群岛" },
                    { key: "MK", name: "马其顿" },
                    { key: "ML", name: "马里" },
                    { key: "MM", name: "缅甸" },
                    { key: "MN", name: "蒙古国；蒙古" },
                    { key: "MO", name: "澳门" },
                    { key: "MP", name: "北马里亚纳群岛" },
                    { key: "MQ", name: "马提尼克" },
                    { key: "MR", name: "毛里塔尼亚" },
                    { key: "MS", name: "蒙塞拉特岛" },
                    { key: "MT", name: "马耳他" },
                    { key: "MU", name: "毛里求斯" },
                    { key: "MV", name: "马尔代夫" },
                    { key: "MW", name: "马拉维" },
                    { key: "MX", name: "墨西哥" },
                    { key: "MY", name: "马来西亚" },
                    { key: "MZ", name: "莫桑比克" },
                    { key: "NA", name: "纳米比亚" },
                    { key: "NC", name: "新喀里多尼亚" },
                    { key: "NE", name: "尼日尔" },
                    { key: "NF", name: "诺福克岛" },
                    { key: "NG", name: "尼日利亚" },
                    { key: "NI", name: "尼加拉瓜" },
                    { key: "NL", name: "荷兰" },
                    { key: "NO", name: "挪威" },
                    { key: "NP", name: "尼泊尔" },
                    { key: "NR", name: "瑙鲁" },
                    { key: "NU", name: "纽埃" },
                    { key: "NZ", name: "新西兰" },
                    { key: "OM", name: "阿曼" },
                    { key: "PA", name: "巴拿马" },
                    { key: "PE", name: "秘鲁" },
                    { key: "PF", name: "法属波利尼西亚" },
                    { key: "PG", name: "巴布亚新几内亚" },
                    { key: "PH", name: "菲律宾" },
                    { key: "PK", name: "巴基斯坦" },
                    { key: "PL", name: "波兰" },
                    { key: "PM", name: "圣皮埃尔和密克隆" },
                    { key: "PN", name: "皮特凯恩群岛" },
                    { key: "PR", name: "波多黎各" },
                    { key: "PS", name: "巴勒斯坦" },
                    { key: "PT", name: "葡萄牙" },
                    { key: "PW", name: "帕劳" },
                    { key: "PY", name: "巴拉圭" },
                    { key: "QA", name: "卡塔尔" },
                    { key: "RE", name: "留尼汪" },
                    { key: "RO", name: "罗马尼亚" },
                    { key: "RS", name: "塞尔维亚" },
                    { key: "RU", name: "俄罗斯" },
                    { key: "RW", name: "卢旺达" },
                    { key: "SA", name: "沙特阿拉伯" },
                    { key: "SB", name: "所罗门群岛" },
                    { key: "SC", name: "塞舌尔" },
                    { key: "SD", name: "苏丹" },
                    { key: "SE", name: "瑞典" },
                    { key: "SG", name: "新加坡" },
                    { key: "SH", name: "圣赫勒拿" },
                    { key: "SI", name: "斯洛文尼亚" },
                    { key: "SJ", name: "斯瓦尔巴群岛和扬马延岛" },
                    { key: "SK", name: "斯洛伐克" },
                    { key: "SL", name: "塞拉利昂" },
                    { key: "SM", name: "圣马力诺" },
                    { key: "SN", name: "塞内加尔" },
                    { key: "SO", name: "索马里" },
                    { key: "SR", name: "苏里南" },
                    { key: "SS", name: "南苏丹" },
                    { key: "ST", name: "圣多美和普林西比" },
                    { key: "SV", name: "萨尔瓦多" },
                    { key: "SX", name: "荷属圣马丁" },
                    { key: "SY", name: "叙利亚" },
                    { key: "SZ", name: "斯威士兰" },
                    { key: "TC", name: "特克斯和凯科斯群岛" },
                    { key: "TD", name: "乍得" },
                    { key: "TF", name: "法属南部领地" },
                    { key: "TG", name: "多哥" },
                    { key: "TH", name: "泰国" },
                    { key: "TJ", name: "塔吉克斯坦" },
                    { key: "TK", name: "托克劳" },
                    { key: "TL", name: "东帝汶" },
                    { key: "TM", name: "土库曼斯坦" },
                    { key: "TN", name: "突尼斯" },
                    { key: "TO", name: "汤加" },
                    { key: "TR", name: "土耳其" },
                    { key: "TT", name: "特立尼达和多巴哥" },
                    { key: "TV", name: "图瓦卢" },
                    { key: "TW", name: "台湾" },
                    { key: "TZ", name: "坦桑尼亚" },
                    { key: "UA", name: "乌克兰" },
                    { key: "UG", name: "乌干达" },
                    { key: "UM", name: "美国本土外小岛屿" },
                    { key: "US", name: "美国" },
                    { key: "UY", name: "乌拉圭" },
                    { key: "UZ", name: "乌兹别克斯坦" },
                    { key: "VA", name: "梵蒂冈" },
                    { key: "VC", name: "圣文森特和格林纳丁斯" },
                    { key: "VE", name: "委内瑞拉" },
                    { key: "VG", name: "英属维尔京群岛" },
                    { key: "VI", name: "美属维尔京群岛" },
                    { key: "VN", name: "越南" },
                    { key: "VU", name: "瓦努阿图" },
                    { key: "WF", name: "瓦利斯和富图纳" },
                    { key: "WS", name: "萨摩亚" },
                    { key: "YE", name: "也门" },
                    { key: "YT", name: "马约特" },
                    { key: "ZA", name: "南非" },
                    { key: "ZM", name: "赞比亚" },
                    { key: "ZW", name: "津巴布韦" },

        ],
        states: {
            US: [
            ]
        }
    }
}).call(this);
