(function () {
    this.App = window.App || {};
    this.App.lang = {
        widgetName: 'AlvaKids widget',
        getTheRightSize: 'Vind de juiste maat voor:',
        continueShopping: 'Ga verder met winkelen',
        helpCenter: 'Help center',
        validation: {
            general: 'Gelieve de informatie in de gemarkeerde velden in te vullen.',
            username: {
                required: 'Geruikersnaam verplicht',
                invalid: "3-20 karakters, letters, nummers, alleen '-' en '_'",
            },
            name: {
                required: 'Geruikersnaam verplicht',
                invalid: "3-20 karakters, letters, nummers, alleen '-' en '_'",
            },
            password: {
                required: 'Wachtwoord verplicht',
                invalid: 'Wachtwoorden dienen uitsluitend uit letters en nummers te bestaan',
                notMatch: "Wachtwoorden zijn niet hetzelfde",
            },
            new_password: {
                required: 'Nieuw wachtwoord verplicht',
                invalid: 'Wachtwoorden dienen uitsluitend uit letters en nummers te bestaan',
                notMatch: "Wachtwoorden zijn niet hetzelfde",
            },
            email: {
                required: 'Emailadres is verplicht',
                invalid: 'Emailadres is niet geldig',
            },
            year: {
                required: 'Jaar is verplicht',
                invalid: 'Jaar is ongeldig',
            },
            month: {
                required: 'Maand is verplicht',
                invalid: 'Maand is ongeldig',
            },
            day: {
                required: 'Dag is verplicht',
                invalid: 'Dag is ongeldig',
            },
            question: {
                required: 'Inhoud verplicht',
            },
            sex: {
                required: 'Geslacht verplicht',
            },
            gender: {
                required: 'Geslacht verplicht',
            },
            state: {
                required: 'Staat is verplicht',
            },
            tandc: {
                required: 'U dient eerst onze gebuikers voorwaarden te accepteren',
            },
            weight: {
                required: 'Gewicht is verplicht',
            },
            height: {
                required: 'Lengte verplicht',
            },
            child_name: {
                required: 'Naam verplicht',
            },
            ethnicity: {
                required: 'Ethniciteit verplicht',
            },
            date_of_birth: {
                required: 'Geboortedatum is verplicht',
                invalid: 'Geboortedatum is ongeldig',
            }
        },
        navigation: {
            back: 'TERUG',
            login: 'Log in',
            signup: 'Registreer',
            getSize: 'Vind de juiste maat',
            continueShopping: 'Ga verder met winkelen',
            manageAccount: 'Account gegevens beheren',
            profiles: 'Profielen',
            logout: 'Log uit',
            changePass: 'Verander uw wachtwoord',
            resetMyPass: 'Wachtwoord opnieuw instellen',
        },
        page: {
            about: 'Over ons',
            howItWorks: 'Hoe werkt het?',
            faq: 'FAQ',
            terms: 'Algemene voorwaarden',
            privacy: 'Privacy beleid',
            help: 'Hulp',
        },
        about: {
            heading: 'Wat is AlvaKids?',
            para1: "AlvaKids is een service voor advies over kledingmaten voor kinderen. Onze service is beschikbaar online en via onze mobiele app voor Android en iPhone.",
            para2: 'Wilt u meer weten over ons? Bezoek onze <a href="#page/faq">"Hulp"</a> pagina voor de veelgestelde vragen of bezoek onze website <a href="http://www.alvakids.com/" target="_blank">www.AlvaKids.com</a>.',
            para3: "Zorgenloos winkelen met AlvaKids!",
            version: "AlvaKids versie v2.0",
        },
        register: {
            header: 'Registreer',
            help: "Het is gratis and neemt 30 seconden",
            userName: 'Gebruikersnaam',
            userNameOrEmail: 'Gebruikersnaam of emailadres',
            gender: 'Geslacht',
            male: 'Man',
            female: 'Vrouw',
            email: 'Emailadres',
            password: 'Wachtwoord',
            confirmPassword: 'Bevestig wachtwoord',
            learnMore: 'Meer info',
            tryFirst: 'Probeer het eerst',
            registerLater: 'Probeer het eerst, registreer later',
            error: 'Registratie mislukt',
            optin: 'Ontvang de AlvaKids nieuwsbrief',
            tandc: 'Ik ga akkoord met <a href="http://alvakids.com/terms_of_use.html" target="_blank">Alva\'s Algemene Voorwaarden</a>.',
            howAltImage: 'img/how-works-img.png',
            description: "AlvaKids helpt u met het vinden van de juiste maat voor kinderkleding. Het werkt eenvoudig: registreer voor uw persoonlijke account via AlvaKids online of via onze mobiele app en maak profielen voor uw kinderen aan.  Zodra de profielen gecreërd zijn zal AlvaKids u advies geven over de juiste kledingmaat, per kledingmerk, per kind. Dit neemt slecht enkele minuten! Over verloop van tijd als uw kinderen langer worden, groeit hun AlvaKids profiel met hun mee, zodat u er zeker van bent dat u de juiste maat nu en in de toekomst vindt. Maar er is meer: zodra u geregistreert bent voor AlvaKids kunt u ook de juiste maat in de winkel vinden door gebruik te maken van onze iPhone en Android applicatie. Download deze app gratis van de app store of Google Play en log in met dezelfde account die u online gebruikt hebt om direct maat advies op uw telefoon te krijgen!",
        },
        settings: {
            editExplanation: 'Voltooi uw account door uw gegevens hieronder in te vullen. Alle velden met een * zijn verplicht.',
            username: 'Gebruikersnaam',
            firstName: 'Voornaam',
            lastName: 'Achternaam',
            email: 'Emailadres',
            password: 'Wachtwoord',
            gender: 'Geslacht',
            country: 'Woonland',
            mobilePhone: 'Mobiele nummer',
            dateOfBirth: 'Geboortedatum',
            state: 'Staat',
            city: 'Woonplaats',
        },
        changePassword: {
            explanation: 'Gebruik uw huidige wachtwoord om dit om te zetten naar een nieuw wachtwoord. Als u uw wachtwoord verloren bent, kunt u uw emailadres hier invullen en dan zullen wij uw wachtwoord opnieuw instellen.',
            currentPassword: 'Huidig wachtwoord',
            newPassword: 'Nieuw wachtwoord',
            repeatNewPassword: 'Herhaal nieuw wachtwoord',
            save: 'Bewaar',
        },
        signup: {       // Signup after try it now
            saveKidProfile: "Om het profiel van uw kind te kunnen bewaren, dient u de missende informatie in te vullen en te registreren met uw eigen naam.",
            reason: "Om het profiel van uw kind te bewaren, dient u te registreren voor een account voor u als gebruiker. Na het registreren van uw naam en contact gegevens kunt u ten alle tijde AlvaKids raadplegen online of via onze mobiele app.",
        },
        login: {
            error: 'Foutmelding!',
        },
        tryNow: {
            addProfile: "Vul hier een profiel voor uw kind in om de juiste maat te vinden.",
            getRecommendation: 'Krijg maat advies',
        },
        miniWidget: {
            updateAndGetSize: "Bewaar en ga naar aanbevelingen",
            helpText: "Controleer of werk de gegevens van uw kind bij.",
        },
        kidProfileAdd: {
            help: 'Maak een profiel voor uw kind om de beste maat te vinden',
            clickToStart: 'Klik hier om profielen aan te maken',
            fillIn: "Vul enkele basis gegevens over uw kind in om advies over de juiste kledingmaat te krijgen.",
            edit: "Nadat u de wijzigingen heeft gemaakt in het profiel; klik op bewaar om ervoor te zorgen dat het vernieuwde profiel is aangepast.",
            uploadPic: '<strong>Voeg een foto van</strong> uw kind toe?',
            name: 'Naam van uw kind',
            gender: 'Geslacht',
            skinny: 'Dun',
            regular: 'Gemiddeld',
            husky: 'Fors',
            longer: 'Lang',
            small: 'Klein',
            shorter: 'Kort',
            medium: 'Gemiddeld',
            big: 'Fors',
            male: 'Jongen',
            female: 'Meisje',
            leg: 'Beenlengte',
            belly: 'Omvang van de buik',
            proportion: 'Lichaamsvorm',
            foot: 'Voet',
            inch: 'inch',
            cm: 'cm',
            kg: 'kg',
            inches: 'inches',
            ft: 'ft/in',
            lbs: 'lbs',
            stone: 'stone',
            stonelbs: 'stone/lbs',
            chooseFt: 'Voeg de schoenmaat of voet lengte toe',
            footSize: 'Voet lengte',
            shoeSize: 'Schoenmaat',
            optional: '(optioneel)',
            save: 'Bewaar profiel',
            wide: 'Brede voeten',
            ethnicity: 'Ethniciteit',
            ethnicities: [
                          { key: "African: Central", name: "Afrikaans: Centraal" },
                          { key: "African: Eastern", name: "Afrikaans: Oostelijk" },
                          { key: "African: Northern", name: "Afrikaans: Noordelijk" },
                          { key: "African: Southern", name: "Afrikaans: Zuidelijk" },
                          { key: "African: Western", name: "Afrikaans: Westers" },
                          { key: "African-American", name: "Afrikaans-Amerikaans" },
                          { key: "Arab/Middle eastern", name: "Arabisch / Midden-oosters" },
                          { key: "Asian: Chinese", name: "Aziatisch: Chinees" },
                          { key: "Asian: Indian/Pakistani", name: "Aziatisch: Indiaas/Pakistaans" },
                          { key: "Asian: Japanese", name: "Aziatisch: Japans" },
                          { key: "Asian: Korean", name: "Aziatisch: Koreaans" },
                          { key: "Asian: South", name: "Aziatisch: Zuidelijk" },
                          { key: "Caribbean/Creole", name: "Caribisch / Creools" },
                          { key: "Caucasian", name: "Blank" },
                          { key: "Hispanic/Latin", name: "Latijn-amerikaans" },
                          { key: "Maori/Aboriginal", name: "Maori/Aboriginal" },
                          { key: "Mediterranean", name: "Mediteraans" },
                          { key: "Native American", name: "Native American" },
                          { key: "Other/Mixed", name: "Anders/Gemixt" },

            ],
        },
        kidProfile: {
            edit: 'Wijzigen',
            gender: 'Geslacht',
            height: 'Lengte',
            weight: 'Gewicht',
            select: 'Selecteer',
        },
        kidsProfiles: {
            intro: "We hebben het profiel van uw kind laten groeien in ons systeem. Gelieve het profiel te verifiëren om ervoor te zorgen dat de informatie klopt met de huidige afmetingen van uw kind.",
            add: 'Klik hier om een profiel toe te voegen',
            kidsImgAlt: "uw kind's profiel",
            height: 'Lengte',
            weight: 'Gewicht',
        },
        faq: {
            header: 'Veelgestelde vragen (FAQ)',
            searchKeyword: 'Zoek op trefwoord',
            faqs: [
                   {
                   question: "Kan ik mijn AlvaKids account ook in de winkel gebruiken?",
                   answer: "Ja! Nadat u uw account gecreërd heeft kunt u inloggen op de mobiele app maar ook op onze online widget op de websites van onze partners. Zodra u iets verandert in uw account, zal dit automatisch synchroniseren op onze online widget en op de mobiele app.",
                   },{
                   question: "Hoe kan ik de profielen aanpassen?",
                   answer: 'Als u de profielen van uw kinderen wenst te wijzigen, kunt u naar de overzichtspagina gaan met al uw profielen. Dit is de eerste pagina die u ziet nadat u bent ingelogd. Naast elk profiel zult u de knop zien om profielen te "wijzigen". Als u hierop klikt krijgt u toegang to het complete profiel van het kind en kunt u direct dingen veranderen.',
                   },{
                   question: "Waarom wil AlvaKids de etniciteit van mijn kind weten?",
                   answer: "Terwijl uw kinderen groeien, zal hun profiel in AlvaKids met hun mee groeien. Om ervoor te zorgen dat onze groei berekening zo correct mogelijk is houden wij rekening met de etniciteit van de kinderen. ",
                   },{
                   question: "Hoe kan ik mijn wachtwoord veranderen?",
                   answer: 'Om uw wachtwoord te veranderen kunt u naar het menu rechtsboven in de hoek gaan. In dit menu zult u de optie "verander wachtwoord" zien staan. Door hierop te klikken zult de pagina openen waarop u uw wachtwoord opnieuw in kunt stellen.',
                   },{
                   question: "Ik ben mijn wachtwoord vergeten,, wat moet ik nu doen?",
                   answer: 'Indien u uw wachtwoord kwijt bent, kunt u dit door ons opnieuw voor u laten instellen. Om dit te doen dient u op de startpagina op "Log in" te klikken. Onder de velden waarin u in kunt loggen zal u de woorden "wachtwoord vergeten?" zien staan. Wanneer u daarop klikt zult u gevraagd worden uw emailadres in te vullen waarna wij u een nieuw wachtwoord via uw geregistreerde email toesturen.',
                   },{
                   question: "Hoe kan ik een profiel verwijderen?",
                   answer: 'On een profiel van een kind te verwijderen kunt u, op de eerste pagina die u ziet na het inloggen, naast het profiel dat u wenst te verwijderen op "wijzigen" klikken. Dit zal het complete profiel van het kind openen waarin u de knop "verwijder profiel" zult zien. Als u op deze knop klikt zult u het complete profiel van het kind verwijderen.',
                   },{
                   question: "Waar kan ik nieuws over AlvaKids krijgen?",
                   answer: "Om op de hoogte te blijven van alles over AlvaKids, kunt u fan van ons worden op <a href='https://www.facebook.com/AlvaKids' target='_blank'>Facebook</a>, ons volgen op twitter <a href='https://twitter.com/AlvaKids' target='_blank'>@AlvaKids</a> of naar onze website <a href='http://www.alvakids.com/' target='_blank'>www.AlvaKids.com</a> gaan en u inschrijven voor onze nieuwsbrief.",
                   },{
                   question: "Wat als uw vraag er niet tussen staat?",
                   answer: "Indien uw vraag ontbreekt, kunt u deze vraag en uw emailadres aan ons doorgeven. Gelieve deze aan de rechterkant in te vullen en dan zullen wij zo spoedig mogelijk contact met u opnemen.",
                   },{
                   question: "Wat als mijn kind te groot is voor AlvaKids?",
                   answer: "AlvaKids is bedoeld voor jongens en meisjes onder de 16 jaar oud. Sommige kinderen zullen echter op jongere leeftijd al te groot zijn voor AlvaKids en dan zullen wij geen goede aanbelelingen kunnen maken. Voor deze kinderen wijzen wij u graag op onze service voor volwassenen <a href='http://www.alvafit.com'>AlvaFit</a>.",
                   },{
                   question: "Wat doet AlvaKids met mijn informatie?",
                   answer: "Wij zullen uw gegevens met zorg behandelen. Voor alle informatie verwijzen we u naar ons <a href='http://www.alvakids.com/privacy_policy.html' target='_blank'>privacybeleid</a> en onze <a href='http://www.alvakids.com/terms_of_use.html' target='_blank'>gebruiksvoorwaarden</a>.",
                   }
            ]
        },
        newQuestion: {
            header: 'Staat uw vraag er niet bij?',
            help: 'Laat het ons weten! Stel uw vraag en vul uw e-mailadres in, dan nemen wij zo spoedig mogelijk contact met u op.',
            submitQuestion: 'Vul uw vraag hier in',
            yourEmail: 'Uw emailadres',
            send: 'Verstuur vraag',
        },
        recommendation: {
            bestSize: 'De beste kledingmaat voor uw kind is ',
            error: 'Het was niet mogelijk om een maat aanbeveling te krijgen',
            noSizeAvailable: 'Geen maat beschikbaar',
            downloadAppReason: 'AlvaKids zal de profielen met uw kinderen laten meegroeien, daardoor zorgen wij ervoor dat u de juiste maat voor uw kinderen zult vinden, nu en in de toekomst. Voor advies over kledingmaten in de winkel kunt u gratis onze Android of iPhone app downloaden en inloggen met dezelfde account die u online heeft gebruikt.',
            registerReason: 'Registreer voor AlvaKids en wij zullen uw profielen bewaren zodat u de beste maat zult vinden voor all verschillende kledingstukken op iedere pagina. Over verloop van tijd zal AlvaKids de profielen van uw kinderen laten groeien om er ook in de toekomst voor te zorgen dat u de juiste maat vindt.',
            saveThisProfile: 'Bewaar dit profiel om een advies te krijgen voor alle kledingstukken op iedere pagina.',
        },
        countries: [
                    { key: "AD", name: "Andorra" },
                    { key: "AE", name: "Verenigde Arabische Emiraten" },
                    { key: "AF", name: "Afghanistan" },
                    { key: "AG", name: "Antigua en Barbuda" },
                    { key: "AI", name: "Anguilla" },
                    { key: "AL", name: "Albanië" },
                    { key: "AM", name: "Armenië" },
                    { key: "AO", name: "Angola" },
                    { key: "AQ", name: "Antarctica" },
                    { key: "AR", name: "Argentinië" },
                    { key: "AS", name: "Amerikaans-Samoa" },
                    { key: "AT", name: "Oostenrijk" },
                    { key: "AU", name: "Australië" },
                    { key: "AW", name: "Aruba" },
                    { key: "AX", name: "Åland" },
                    { key: "AZ", name: "Azerbeidzjan" },
                    { key: "BA", name: "Bosnië-Herzegovina" },
                    { key: "BB", name: "Barbados" },
                    { key: "BD", name: "Bangladesh" },
                    { key: "BE", name: "België" },
                    { key: "BF", name: "Burkina Faso" },
                    { key: "BG", name: "Bulgarije" },
                    { key: "BH", name: "Bahrein" },
                    { key: "BI", name: "Burundi" },
                    { key: "BJ", name: "Benin" },
                    { key: "BL", name: "Saint-Barthélemy" },
                    { key: "BM", name: "Bermuda" },
                    { key: "BN", name: "Brunei" },
                    { key: "BO", name: "Bolivië" },
                    { key: "BQ", name: "Bonaire, Sint Eustatius en Saba" },
                    { key: "BR", name: "Brazilië" },
                    { key: "BS", name: "Bahama's" },
                    { key: "BT", name: "Bhutan" },
                    { key: "BV", name: "Bouvet Eiland" },
                    { key: "BW", name: "Botswana" },
                    { key: "BY", name: "Belarus" },
                    { key: "BZ", name: "Belize" },
                    { key: "CA", name: "Canada" },
                    { key: "CC", name: "Cocos" },
                    { key: "CD", name: "Congo (Democratische Republiek)" },
                    { key: "CF", name: "Centraal-Afrikaanse Republiek" },
                    { key: "CG", name: "Congo (Volksrepubliek)" },
                    { key: "CH", name: "Zwitserland" },
                    { key: "CI", name: "Ivoorkust" },
                    { key: "CK", name: "Cook" },
                    { key: "CL", name: "Chili" },
                    { key: "CM", name: "Kameroen" },
                    { key: "CN", name: "China" },
                    { key: "CO", name: "Colombia" },
                    { key: "CR", name: "Costa Rica" },
                    { key: "CU", name: "Cuba" },
                    { key: "CV", name: "Kaapverdië" },
                    { key: "CW", name: "Curaçao" },
                    { key: "CX", name: "Christmaseiland" },
                    { key: "CY", name: "Cyprus" },
                    { key: "CZ", name: "Tsjechië" },
                    { key: "DE", name: "Duitsland" },
                    { key: "DJ", name: "Djibouti" },
                    { key: "DK", name: "Denemarken" },
                    { key: "DM", name: "Dominica" },
                    { key: "DO", name: "Dominicaanse Republiek" },
                    { key: "DZ", name: "Algerije" },
                    { key: "EC", name: "Ecuador" },
                    { key: "EE", name: "Estland" },
                    { key: "EG", name: "Egypte" },
                    { key: "EH", name: "Westelijke Sahara" },
                    { key: "ER", name: "Eritrea" },
                    { key: "ES", name: "Spanje" },
                    { key: "ET", name: "Ethiopië" },
                    { key: "FI", name: "Finland" },
                    { key: "FJ", name: "Fiji" },
                    { key: "FK", name: "Falkland" },
                    { key: "FM", name: "Micronesië" },
                    { key: "FO", name: "Faeröer" },
                    { key: "FR", name: "Frankrijk" },
                    { key: "GA", name: "Gabon" },
                    { key: "GB", name: "Verenigd Koninkrijk" },
                    { key: "GD", name: "Grenada" },
                    { key: "GE", name: "Georgië" },
                    { key: "GF", name: "Frans-Guyana" },
                    { key: "GG", name: "Guernsey" },
                    { key: "GH", name: "Ghana" },
                    { key: "GI", name: "Gibraltar" },
                    { key: "GL", name: "Groenland" },
                    { key: "GM", name: "Gambia" },
                    { key: "GN", name: "Guinea" },
                    { key: "GP", name: "Guadeloupe" },
                    { key: "GQ", name: "Equatoriaal-Guinea" },
                    { key: "GR", name: "Griekenland" },
                    { key: "GS", name: "Zuid-Georgia en de Zuidelijke Sandwicheilanden" },
                    { key: "GT", name: "Guatemala" },
                    { key: "GU", name: "Guam" },
                    { key: "GW", name: "Guinee-Bissau" },
                    { key: "GY", name: "Guyana" },
                    { key: "HK", name: "Hongkong" },
                    { key: "HM", name: "Heard en McDonald" },
                    { key: "HN", name: "Honduras" },
                    { key: "HR", name: "Kroatië" },
                    { key: "HT", name: "Haïti" },
                    { key: "HU", name: "Hongarije" },
                    { key: "ID", name: "Indonesië" },
                    { key: "IE", name: "Ierland" },
                    { key: "IL", name: "Israël" },
                    { key: "IM", name: "Eiland Man" },
                    { key: "IN", name: "India" },
                    { key: "IO", name: "Brits Indische oceaan" },
                    { key: "IQ", name: "Irak" },
                    { key: "IR", name: "Iran" },
                    { key: "IS", name: "IJsland" },
                    { key: "IT", name: "Italië" },
                    { key: "JE", name: "Jersey" },
                    { key: "JM", name: "Jamaica" },
                    { key: "JO", name: "Jordanië" },
                    { key: "JP", name: "Japan" },
                    { key: "KE", name: "Kenia" },
                    { key: "KG", name: "Kirgizstan" },
                    { key: "KH", name: "Cambodja" },
                    { key: "KI", name: "Kiribati" },
                    { key: "KM", name: "Comoren (Unie)" },
                    { key: "KN", name: "Sint-Kitts en Nevis (Federatie)" },
                    { key: "KP", name: "Noord-Korea" },
                    { key: "KR", name: "Zuid-Korea" },
                    { key: "KW", name: "Koeweit" },
                    { key: "KY", name: "Caymaneilanden" },
                    { key: "KZ", name: "Kazachstan" },
                    { key: "LA", name: "Laos" },
                    { key: "LB", name: "Libanon" },
                    { key: "LC", name: "Saint Lucia" },
                    { key: "LI", name: "Liechtenstein" },
                    { key: "LK", name: "Sri Lanka" },
                    { key: "LR", name: "Liberia" },
                    { key: "LS", name: "Lesotho" },
                    { key: "LT", name: "Litouwen" },
                    { key: "LU", name: "Luxemburg" },
                    { key: "LV", name: "Letland" },
                    { key: "LY", name: "Libië" },
                    { key: "MA", name: "Marokko" },
                    { key: "MC", name: "Monaco" },
                    { key: "MD", name: "Moldavië" },
                    { key: "ME", name: "Montenegro" },
                    { key: "MF", name: "Sint-Maarten (Frans deel)" },
                    { key: "MG", name: "Madagaskar" },
                    { key: "MH", name: "Marshall" },
                    { key: "MK", name: "Macedonië" },
                    { key: "ML", name: "Mali" },
                    { key: "MM", name: "Myanmar (Unie)" },
                    { key: "MN", name: "Mongolië" },
                    { key: "MO", name: "Macao" },
                    { key: "MP", name: "Noordelijke Marianen" },
                    { key: "MQ", name: "Martinique" },
                    { key: "MR", name: "Mauritanië" },
                    { key: "MS", name: "Montserrat" },
                    { key: "MT", name: "Malta" },
                    { key: "MU", name: "Mauritius" },
                    { key: "MV", name: "Maldiven" },
                    { key: "MW", name: "Malawi" },
                    { key: "MX", name: "Mexico" },
                    { key: "MY", name: "Maleisië" },
                    { key: "MZ", name: "Mozambique" },
                    { key: "NA", name: "Namibië" },
                    { key: "NC", name: "Nieuw-Caledonië" },
                    { key: "NE", name: "Niger" },
                    { key: "NF", name: "Norfolk" },
                    { key: "NG", name: "Nigeria" },
                    { key: "NI", name: "Nicaragua" },
                    { key: "NL", name: "Nederland" },
                    { key: "NO", name: "Noorwegen" },
                    { key: "NP", name: "Nepal" },
                    { key: "NR", name: "Nauru" },
                    { key: "NU", name: "Niue" },
                    { key: "NZ", name: "Nieuw-Zeeland" },
                    { key: "OM", name: "Oman (Sultanaat)" },
                    { key: "PA", name: "Panama" },
                    { key: "PE", name: "Peru" },
                    { key: "PF", name: "Frans-Polynesië" },
                    { key: "PG", name: "Papoea-Nieuw-Guinea" },
                    { key: "PH", name: "Filipijnen" },
                    { key: "PK", name: "Pakistan" },
                    { key: "PL", name: "Polen" },
                    { key: "PM", name: "Saint-Pierre en Miquelon" },
                    { key: "PN", name: "Pitcairn" },
                    { key: "PR", name: "Puerto Rico" },
                    { key: "PS", name: "Palestina" },
                    { key: "PT", name: "Portugal" },
                    { key: "PW", name: "Palau" },
                    { key: "PY", name: "Paraguay" },
                    { key: "QA", name: "Qatar" },
                    { key: "RE", name: "Réunion" },
                    { key: "RO", name: "Roemenië" },
                    { key: "RS", name: "Servië" },
                    { key: "RU", name: "Rusland" },
                    { key: "RW", name: "Rwanda" },
                    { key: "SA", name: "Saudi-Arabië" },
                    { key: "SB", name: "Salomon" },
                    { key: "SC", name: "Seychellen" },
                    { key: "SD", name: "Soedan" },
                    { key: "SE", name: "Zweden" },
                    { key: "SG", name: "Singapore" },
                    { key: "SH", name: "Saint Helena" },
                    { key: "SI", name: "Slovenië" },
                    { key: "SJ", name: "Spitsbergen en Jan Mayen" },
                    { key: "SK", name: "Slowakije" },
                    { key: "SL", name: "Sierra Leone" },
                    { key: "SM", name: "San Marino" },
                    { key: "SN", name: "Senegal" },
                    { key: "SO", name: "Somalië" },
                    { key: "SR", name: "Suriname" },
                    { key: "SS", name: "Zuid-Soedan" },
                    { key: "ST", name: "São Tomé en Principe" },
                    { key: "SV", name: "El Salvador" },
                    { key: "SX", name: "Sint Maarten (Nederlands deel)" },
                    { key: "SY", name: "Syrië" },
                    { key: "SZ", name: "Ngwane (Koninkrijk Swaziland)" },
                    { key: "TC", name: "Turks- en Caicoseilanden" },
                    { key: "TD", name: "Tsjaad" },
                    { key: "TF", name: "Franse Zuidelijke Gebieden" },
                    { key: "TG", name: "Togo" },
                    { key: "TH", name: "Thailand" },
                    { key: "TJ", name: "Tadzjikistan" },
                    { key: "TK", name: "Tokelau" },
                    { key: "TL", name: "Timor Leste" },
                    { key: "TM", name: "Turkmenistan" },
                    { key: "TN", name: "Tunesië" },
                    { key: "TO", name: "Tonga" },
                    { key: "TR", name: "Turkije" },
                    { key: "TT", name: "Trinidad en Tobago" },
                    { key: "TV", name: "Tuvalu" },
                    { key: "TW", name: "Taiwan" },
                    { key: "TZ", name: "Tanzania" },
                    { key: "UA", name: "Oekraïne" },
                    { key: "UG", name: "Uganda" },
                    { key: "UM", name: "Ver afgelegen eilandjes van de Verenigde Staten" },
                    { key: "US", name: "Verenigde Staten van Amerika" },
                    { key: "UY", name: "Uruguay" },
                    { key: "UZ", name: "Oezbekistan" },
                    { key: "VA", name: "Heilige Stoel" },
                    { key: "VC", name: "Saint Vincent en de Grenadines" },
                    { key: "VE", name: "Venezuela" },
                    { key: "VG", name: "Britse Maagdeneilanden" },
                    { key: "VI", name: "Amerikaanse Maagdeneilanden" },
                    { key: "VN", name: "Vietnam" },
                    { key: "VU", name: "Vanuatu" },
                    { key: "WF", name: "Wallis en Futuna" },
                    { key: "WS", name: "Samoa" },
                    { key: "YE", name: "Jemen" },
                    { key: "YT", name: "Mayotte" },
                    { key: "ZA", name: "Zuid-Afrika" },
                    { key: "ZM", name: "Zambia" },
                    { key: "ZW", name: "Zimbabwe" }
        ],
        states: {
            US: [
            ]
        }
    }
}).call(this);
