(function () {
    this.App = window.App || {};
    this.App.lang = {
        widgetName: 'AlvaKids Widget',
        getTheRightSize: 'Get the right size',
        continueShopping: 'Continue shopping',
        helpCenter: 'Help Centre',
        validation: {
            general: 'Please fix the highlighted fields',
            username: {
                required: 'User name required',
                invalid: "3-20 characters. letter, numeric, '-' and '_' only"
            },
            name: {
                required: 'User name required',
                invalid: "3-20 characters. letter, numeric, '-' and '_' only"
            },
            password: {
                required: 'Password required',
                invalid: 'Passwords must be letter and numeric only',
                notMatch: "Passwords don't match"
            },
            new_password: {
                required: 'New password required',
                invalid: 'Passwords must be letter and numeric only',
                notMatch: "Passwords don't match"
            },
            email: {
                required: 'Email required',
                invalid: 'Email is not valid'
            },
            year: {
                required: 'Year required',
                invalid: 'Year is not valid'
            },
            month: {
                required: 'Month required',
                invalid: 'Month is not valid'
            },
            day: {
                required: 'Day required',
                invalid: 'Day is not valid'
            },
            question: {
                required: 'Content required'
            },
            sex: {
                required: 'Gender required'
            },
            gender: {
                required: 'Gender required'
            },
            state: {
                required: 'State required'
            },
            tandc: {
                required: 'You must accept the terms of use'
            },
            weight: {
                required: 'Weight required'
            },
            height: {
                required: 'Height required'
            },
            child_name: {
                required: 'Name required'
            },
            ethnicity: {
                required: 'Ethnicity required'
            },
            date_of_birth: {
                required: 'Date of birth is required',
                invalid: 'Date of birth is invalid'
            }
        },
        navigation: {
            back: 'BACK',
            login: 'Log in',
            signup: 'Sign Up',
            getSize: 'Get size',
            continueShopping: 'Continue shopping',
            manageAccount: 'Manage Account',
            profiles: 'Profiles',
            logout: 'Log out',
            changePass: 'Change Password',
            resetMyPass: 'Reset my password'
        },
        page: {
            about: 'About us',
            howItWorks: 'How does it work?',
            faq: 'FAQ',
            terms: 'Terms of Use',
            privacy: 'Privacy Policy',
            help: 'Help'
        },
        about: {
            heading: 'What is AlvaKids?',
            para1: "AlvaKids is a service that provides size recommendations for kids' clothing. Our service is available online and through a mobile application for Android and iOS.",
            para2: 'Want to know more? Please go to the <a href="#page/faq">Help section</a> to consult our FAQ or visit us on <a href="http://www.alvakids.com/" target="_blank">www.AlvaKids.com</a>.',
            para3: "Enjoy your shopping with AlvaKids!",
            version: "AlvaKids version v2.0",
        },
        register: {
            header: 'Register',
            help: "It's free and takes 30 seconds",
            userName: 'User name',
            userNameOrEmail: 'User name or Email address',
            gender: 'Gender',
            male: 'Male',
            female: 'Female',
            email: 'Email address',
            password: 'Password',
            confirmPassword: 'Confirm password',
            learnMore: 'Learn more',
            tryFirst: 'Try it first',
            registerLater: 'Try first, register later',
            error: 'Sign-up failed',
            optin: 'Get the AlvaKids newsletter',
            tandc: 'I agree with Alva\'s <a href="http://alvakids.com/terms_of_use.html" target="_blank">terms of use</a>.',
            howAltImage: 'img/how-works-img.png',
            description: "AlvaKids helps you find the right size for your kids'clothing. Using AlvaKids is very easy; register as an account holder, then create profiles for your kids using their basic measurements. AlvaKids will then generate the best size for your kids for any brand of clothing. It's that easy! Over time AlvaKids make each profile grow with your child, to make sure you get accurate sizing recommendations now and in the future. But does it not end there; after you register with AlvaKids, you can get size recommendations in-store by downloading our AlvaKids mobile application from the iTunes App Store or the Google Play Store. Download the app for free and login with the same account you have used online to receive size recommendation on your phone instantly!",
        },
        settings: {
            editExplanation: 'Complete your account by entering your information below. All fields marked with an * are required.',
            username: 'User name',
            firstName: 'First name',
            lastName: 'Last name',
            email: 'Email address',
            password: 'Password',
            gender: 'Gender',
            country: 'Country of residence',
            mobilePhone: 'Mobile phone',
            dateOfBirth: 'Date of birth',
            state: 'State',
            city: 'City of residence',
        },
        changePassword: {
            explanation: 'Use your current password to create a new password. If you have lost your password please submit your email address here and we will reset your password and send it to your email address.',
            currentPassword: 'Current password',
            newPassword: 'New password',
            repeatNewPassword: 'Repeat new password',
            save: 'Save',
        },
        signup: {       // Signup after try it now
            saveKidProfile: "To save your kid's profile, please fill in the missing information and register under your own name.",
            reason: "In order for us to store your kid's profile we need you to register your own user details. After registering your name and basic contact details you will then be able to receive accurate sizing recommendations online and through our mobile app!",
        },
        login: {
            error: 'Error!',
        },
        tryNow: {
            addProfile: "Please fill in your kid's basic measurements to get a recommendation.",
            getRecommendation: 'Get recommendation',
        },
        miniWidget: {
            updateAndGetSize: "Update and Get Size",
            helpText: "Please check or update your child's details.",
        },
        kidProfileAdd: {
            help: 'Create a profile for your kid to get the right size.',
            clickToStart: 'Click here to start adding kid profiles',
            fillIn: "Fill in your kid's basic measurements to get a recommendation.",
            edit: "After editing, click 'save profile' to make sure the changes are stored.",
            uploadPic: '<strong>Upload a profile picture</strong> of your kid?',
            name: 'Name of your kid',
            gender: 'Gender',
            skinny: 'Skinny',
            regular: 'Regular',
            husky: 'Plus/husky',
            longer: 'Longer',
            small: 'Small',
            shorter: 'Shorter',
            medium: 'Medium',
            big: 'Big',
            male: 'Boy',
            female: 'Girl',
            leg: 'Leg proportion',
            belly: 'Belly size',
            proportion: 'Body shape',
            foot: 'Foot',
            inch: 'inch',
            cm: 'cm',
            kg: 'kg',
            inches: 'inches',
            ft: 'ft/in',
            lbs: 'lbs',
            stone: 'stone',
            stonelbs: 'stone/lbs',
            chooseFt: 'Add shoe or foot size',
            footSize: 'Foot size',
            shoeSize: 'Shoe size',
            optional: '(optional)',
            save: 'Save profile',
            wide: 'Wide feet',
            ethnicity: 'Ethnicity',
            ethnicities: [
                { key: 'African: Central', name: 'African: Central' },
                { key: 'African: Eastern', name: 'African: Eastern' },
                { key: 'African: Northern', name: 'African: Northern' },
                { key: 'African: Southern', name: 'African: Southern' },
                { key: 'African: Western', name: 'African: Western' },
                { key: 'African-American', name: 'African-American' },
                { key: 'Arab/Middle eastern', name: 'Arab/Middle eastern' },
                { key: 'Asian: Chinese', name: 'Asian: Chinese' },
                { key: 'Asian: Indian/Pakistani', name: 'Asian: Indian/Pakistani' },
                { key: 'Asian: Japanese', name: 'Asian: Japanese' },
                { key: 'Asian: Korean', name: 'Asian: Korean' },
                { key: 'Asian: South', name: 'Asian: South' },
                { key: 'Caribbean/Creole', name: 'Caribbean/Creole' },
                { key: 'Caucasian', name: 'Caucasian' },
                { key: 'Hispanic/Latin', name: 'Hispanic/Latin' },
                { key: 'Maori/Aboriginal', name: 'Maori/Aboriginal' },
                { key: 'Mediterranean', name: 'Mediterranean' },
                { key: 'Native American', name: 'Native American' },
                { key: 'Other/mixed', name: 'Other/mixed' }
            ],
        },
        kidProfile: {
            edit: 'Edit',
            gender: 'Gender',
            updated: 'Last updated:',
            height: 'Height',
            weight: 'Weight',
            select: 'Select',
        },
        kidsProfiles: {
            intro: "We have made your kid's profile grow in our system. Please check the profile to make sure the updated information matches your kid's current measurements.",
            add: 'Click here to add a profile',
            kidsImgAlt: 'your kids profile',
            height: 'Height',
            weight: 'Weight',
        },
        faq: {
            header: 'Frequently Asked Questions',
            searchKeyword: 'Search by keyword',
            faqs: [
                   {
                   question: "Can I use my AlvaKids account in-store?",
                   answer: "Yes! After registering for AlvaKids you can use your account both online and on the mobile application. When you update your account or your kids profiles, the information will then be automatically updated both online and on your mobile application.",
                   },{
                   question: "How do I edit my kids profiles?",
                   answer: "If you would like to make changes in the kids profiles, simply click edit in the profiles overview page that you will see straight after logging in. There you will be able to modify all your saved profiles.",
                   },{
                   question: "Why does AlvaKids ask for my kids' ethnicity?",
                   answer: "When your kids grow, their AlvaKids profiles will grow with them. Our growth calculation takes ethnicity into account to make sure you get accurate recommendations now and in the future.",
                   },{
                   question: "How do I change my password?",
                   answer: 'To change your password go to the menu on the top right where you see your username. When you click on your username this menu will fold out. There you will find the option to "change password". Clicking on this will refer you to the page where you can change your password.',
                   },{
                   question: "I forgot my password, what do I do?",
                   answer: 'If you have lost your password, click Login on the home page. Underneath the Login fields you will see "Forgot Password?". Clicking this will require you to enter the e-mail address that you have linked to this account. After submitting your e-mail address we will send a new password to you via e-mail.',
                   },{
                   question: "How do I delete a profile?",
                   answer: "To delete a kid's profile simply click Edit on the Kids's Profile Overview page and select the 'Delete Profile' option in the profile you would like to delete. Your child's profile will then be deleted from your account.",
                   },{
                   question: "Where can I get news on AlvaKids?",
                   answer: 'To learn more about AlvaKids go to our <a href="https://www.facebook.com/AlvaKids" target="_blank">Facebook</a> page, follow us on Twitter <a href="https://twitter.com/AlvaKids" target="_blank">@AlvaKids</a> or visit <a href="http://www.alvakids.com/" target="_blank">www.AlvaKids.com</a> to find out more about our service and to subscribe to our newsletter.',
                   },{
                   question: "What if my question is not here?",
                   answer: "If your question is not here, please send us your question and your e-mail address on the right hand side and we will get back to you as soon as possible.",
                   },{
                   question: "What if my kid is too big for AlvaKids?",
                   answer: 'AlvaKids is for girls and boys under the age of 16. Some younger kids may be too large for AlvaKids in which case we will not be able to generate a recommendation. For these kids we refer you to our adult sizing recommendation service called <a href="http://www.alvafit.com">AlvaFit</a>.',
                   },{
                   question: "What does AlvaKids do with my information?",
                   answer: 'We will handle your information with care, for more information please look at the <a href="http://www.alvakids.com/privacy_policy.html" target="_blank">privacy policy</a> and <a href="http://www.alvakids.com/terms_of_use.html" target="_blank">the terms of use</a>.',
                   },
                ]
        },
        newQuestion: {
            header: 'Could not find your question?',
            help: 'Let us know! Submit your question and your email address below and we will get back to you as soon as possible.',
            submitQuestion: 'Submit your question here',
            yourEmail: 'Your email address',
            send: 'Send question'
        },
        recommendation: {
            bestSize: 'The best size for your kid is:',
            error: 'Unable to get size recommendation',
            noSizeAvailable: 'No size available',
            downloadAppReason: 'AlvaKids will make each profile grow with your kid to make sure you get the right size now and in the future.<br/>To get size recommendations in-store download the AlvaKids app for free from the iTunes app store or Google Play and login in with the same account you have used online.',
            registerReason: 'Register for AlvaKids and we will store your profiles to provide you with accurate size recommendations for each item. Over time AlvaKids will also make the profiles grow to make sure you get the right size now and in the future.',
            saveThisProfile: 'Save this profile to get a recommendation for all items on every page.'
        },
        countries: [
            { key: 'AF', name: 'Afghanistan' },
            { key: 'AL', name: 'Albania' },
            { key: 'DZ', name: 'Algeria' },
            { key: 'AS', name: 'American Samoa' },
            { key: 'AD', name: 'Andorra' },
            { key: 'AO', name: 'Angola' },
            { key: 'AI', name: 'Anguilla' },
            { key: 'AQ', name: 'Antarctica' },
            { key: 'AG', name: 'Antigua and Barbuda' },
            { key: 'AR', name: 'Argentina' },
            { key: 'AM', name: 'Armenia' },
            { key: 'AW', name: 'Aruba' },
            { key: 'AU', name: 'Australia' },
            { key: 'AT', name: 'Austria' },
            { key: 'AZ', name: 'Azerbaijan' },
            { key: 'BS', name: 'Bahamas' },
            { key: 'BH', name: 'Bahrain' },
            { key: 'BD', name: 'Bangladesh' },
            { key: 'BB', name: 'Barbados' },
            { key: 'BY', name: 'Belarus' },
            { key: 'BE', name: 'Belgium' },
            { key: 'BZ', name: 'Belize' },
            { key: 'BJ', name: 'Benin' },
            { key: 'BM', name: 'Bermuda' },
            { key: 'BT', name: 'Bhutan' },
            { key: 'BO', name: 'Bolivia' },
            { key: 'BA', name: 'Bosnia and Herzegovina' },
            { key: 'BW', name: 'Botswana' },
            { key: 'BV', name: 'Bouvet Island' },
            { key: 'BR', name: 'Brazil' },
            { key: 'IO', name: 'British Indian Ocean Territory' },
            { key: 'BN', name: 'Brunei Darussalam' },
            { key: 'BG', name: 'Bulgaria' },
            { key: 'BF', name: 'Burkina Faso' },
            { key: 'BI', name: 'Burundi' },
            { key: 'KH', name: 'Cambodia' },
            { key: 'CM', name: 'Cameroon' },
            { key: 'CA', name: 'Canada' },
            { key: 'CV', name: 'Cape Verde' },
            { key: 'KY', name: 'Cayman Islands' },
            { key: 'CF', name: 'Central African Republic' },
            { key: 'TD', name: 'Chad' },
            { key: 'CL', name: 'Chile' },
            { key: 'CN', name: 'China' },
            { key: 'CX', name: 'Christmas Island' },
            { key: 'CC', name: 'Cocos (Keeling) Islands' },
            { key: 'CO', name: 'Colombia' },
            { key: 'KM', name: 'Comoros' },
            { key: 'CG', name: 'Congo' },
            { key: 'CD', name: 'Congo, the Democratic Republic of the' },
            { key: 'CK', name: 'Cook Islands' },
            { key: 'CR', name: 'Costa Rica' },
            { key: 'CI', name: 'Cote D&apos;Ivoire' },
            { key: 'HR', name: 'Croatia' },
            { key: 'CU', name: 'Cuba' },
            { key: 'CY', name: 'Cyprus' },
            { key: 'CZ', name: 'Czech Republic' },
            { key: 'DK', name: 'Denmark' },
            { key: 'DJ', name: 'Djibouti' },
            { key: 'DM', name: 'Dominica' },
            { key: 'DO', name: 'Dominican Republic' },
            { key: 'EC', name: 'Ecuador' },
            { key: 'EG', name: 'Egypt' },
            { key: 'SV', name: 'El Salvador' },
            { key: 'GQ', name: 'Equatorial Guinea' },
            { key: 'ER', name: 'Eritrea' },
            { key: 'EE', name: 'Estonia' },
            { key: 'ET', name: 'Ethiopia' },
            { key: 'FK', name: 'Falkland Islands (Malvinas)' },
            { key: 'FO', name: 'Faroe Islands' },
            { key: 'FJ', name: 'Fiji' },
            { key: 'FI', name: 'Finland' },
            { key: 'FR', name: 'France' },
            { key: 'GF', name: 'French Guiana' },
            { key: 'PF', name: 'French Polynesia' },
            { key: 'TF', name: 'French Southern Territories' },
            { key: 'GA', name: 'Gabon' },
            { key: 'GM', name: 'Gambia' },
            { key: 'GE', name: 'Georgia' },
            { key: 'DE', name: 'Germany' },
            { key: 'GH', name: 'Ghana' },
            { key: 'GI', name: 'Gibraltar' },
            { key: 'GR', name: 'Greece' },
            { key: 'GL', name: 'Greenland' },
            { key: 'GD', name: 'Grenada' },
            { key: 'GP', name: 'Guadeloupe' },
            { key: 'GU', name: 'Guam' },
            { key: 'GT', name: 'Guatemala' },
            { key: 'GN', name: 'Guinea' },
            { key: 'GW', name: 'Guinea-Bissau' },
            { key: 'GY', name: 'Guyana' },
            { key: 'HT', name: 'Haiti' },
            { key: 'HM', name: 'Heard Island and Mcdonald Islands' },
            { key: 'VA', name: 'Holy See (Vatican City State)' },
            { key: 'HN', name: 'Honduras' },
            { key: 'HK', name: 'Hong Kong' },
            { key: 'HU', name: 'Hungary' },
            { key: 'IS', name: 'Iceland' },
            { key: 'IN', name: 'India' },
            { key: 'ID', name: 'Indonesia' },
            { key: 'IR', name: 'Iran, Islamic Republic of' },
            { key: 'IQ', name: 'Iraq' },
            { key: 'IE', name: 'Ireland' },
            { key: 'IL', name: 'Israel' },
            { key: 'IT', name: 'Italy' },
            { key: 'JM', name: 'Jamaica' },
            { key: 'JP', name: 'Japan' },
            { key: 'JO', name: 'Jordan' },
            { key: 'KZ', name: 'Kazakhstan' },
            { key: 'KE', name: 'Kenya' },
            { key: 'KI', name: 'Kiribati' },
            { key: 'KP', name: 'Korea, Democratic People&apos;s Republic of' },
            { key: 'KR', name: 'Korea, Republic of' },
            { key: 'KW', name: 'Kuwait' },
            { key: 'KG', name: 'Kyrgyzstan' },
            { key: 'LA', name: 'Lao People&apos;s Democratic Republic' },
            { key: 'LV', name: 'Latvia' },
            { key: 'LB', name: 'Lebanon' },
            { key: 'LS', name: 'Lesotho' },
            { key: 'LR', name: 'Liberia' },
            { key: 'LY', name: 'Libyan Arab Jamahiriya' },
            { key: 'LI', name: 'Liechtenstein' },
            { key: 'LT', name: 'Lithuania' },
            { key: 'LU', name: 'Luxembourg' },
            { key: 'MO', name: 'Macao' },
            { key: 'MK', name: 'Macedonia, the Former Yugoslav Republic of' },
            { key: 'MG', name: 'Madagascar' },
            { key: 'MW', name: 'Malawi' },
            { key: 'MY', name: 'Malaysia' },
            { key: 'MV', name: 'Maldives' },
            { key: 'ML', name: 'Mali' },
            { key: 'MT', name: 'Malta' },
            { key: 'MH', name: 'Marshall Islands' },
            { key: 'MQ', name: 'Martinique' },
            { key: 'MR', name: 'Mauritania' },
            { key: 'MU', name: 'Mauritius' },
            { key: 'YT', name: 'Mayotte' },
            { key: 'MX', name: 'Mexico' },
            { key: 'FM', name: 'Micronesia, Federated States of' },
            { key: 'MD', name: 'Moldova, Republic of' },
            { key: 'MC', name: 'Monaco' },
            { key: 'MN', name: 'Mongolia' },
            { key: 'MS', name: 'Montserrat' },
            { key: 'MA', name: 'Morocco' },
            { key: 'MZ', name: 'Mozambique' },
            { key: 'MM', name: 'Myanmar' },
            { key: 'NA', name: 'Namibia' },
            { key: 'NR', name: 'Nauru' },
            { key: 'NP', name: 'Nepal' },
            { key: 'NL', name: 'Netherlands' },
            { key: 'AN', name: 'Netherlands Antilles' },
            { key: 'NC', name: 'New Caledonia' },
            { key: 'NZ', name: 'New Zealand' },
            { key: 'NI', name: 'Nicaragua' },
            { key: 'NE', name: 'Niger' },
            { key: 'NG', name: 'Nigeria' },
            { key: 'NU', name: 'Niue' },
            { key: 'NF', name: 'Norfolk Island' },
            { key: 'MP', name: 'Northern Mariana Islands' },
            { key: 'NO', name: 'Norway' },
            { key: 'OM', name: 'Oman' },
            { key: 'PK', name: 'Pakistan' },
            { key: 'PW', name: 'Palau' },
            { key: 'PS', name: 'Palestinian Territory, Occupied' },
            { key: 'PA', name: 'Panama' },
            { key: 'PG', name: 'Papua New Guinea' },
            { key: 'PY', name: 'Paraguay' },
            { key: 'PE', name: 'Peru' },
            { key: 'PH', name: 'Philippines' },
            { key: 'PN', name: 'Pitcairn' },
            { key: 'PL', name: 'Poland' },
            { key: 'PT', name: 'Portugal' },
            { key: 'PR', name: 'Puerto Rico' },
            { key: 'QA', name: 'Qatar' },
            { key: 'RE', name: 'Reunion' },
            { key: 'RO', name: 'Romania' },
            { key: 'RU', name: 'Russian Federation' },
            { key: 'RW', name: 'Rwanda' },
            { key: 'SH', name: 'Saint Helena' },
            { key: 'KN', name: 'Saint Kitts and Nevis' },
            { key: 'LC', name: 'Saint Lucia' },
            { key: 'PM', name: 'Saint Pierre and Miquelon' },
            { key: 'VC', name: 'Saint Vincent and the Grenadines' },
            { key: 'WS', name: 'Samoa' },
            { key: 'SM', name: 'San Marino' },
            { key: 'ST', name: 'Sao Tome and Principe' },
            { key: 'SA', name: 'Saudi Arabia' },
            { key: 'SN', name: 'Senegal' },
            { key: 'CS', name: 'Serbia and Montenegro' },
            { key: 'SC', name: 'Seychelles' },
            { key: 'SL', name: 'Sierra Leone' },
            { key: 'SG', name: 'Singapore' },
            { key: 'SK', name: 'Slovakia' },
            { key: 'SI', name: 'Slovenia' },
            { key: 'SB', name: 'Solomon Islands' },
            { key: 'SO', name: 'Somalia' },
            { key: 'ZA', name: 'South Africa' },
            { key: 'GS', name: 'South Georgia and the South Sandwich Islands' },
            { key: 'ES', name: 'Spain' },
            { key: 'LK', name: 'Sri Lanka' },
            { key: 'SD', name: 'Sudan' },
            { key: 'SR', name: 'Suriname' },
            { key: 'SJ', name: 'Svalbard and Jan Mayen' },
            { key: 'SZ', name: 'Swaziland' },
            { key: 'SE', name: 'Sweden' },
            { key: 'CH', name: 'Switzerland' },
            { key: 'SY', name: 'Syrian Arab Republic' },
            { key: 'TW', name: 'Taiwan, Province of China' },
            { key: 'TJ', name: 'Tajikistan' },
            { key: 'TZ', name: 'Tanzania, United Republic of' },
            { key: 'TH', name: 'Thailand' },
            { key: 'TL', name: 'Timor-Leste' },
            { key: 'TG', name: 'Togo' },
            { key: 'TK', name: 'Tokelau' },
            { key: 'TO', name: 'Tonga' },
            { key: 'TT', name: 'Trinidad and Tobago' },
            { key: 'TN', name: 'Tunisia' },
            { key: 'TR', name: 'Turkey' },
            { key: 'TM', name: 'Turkmenistan' },
            { key: 'TC', name: 'Turks and Caicos Islands' },
            { key: 'TV', name: 'Tuvalu' },
            { key: 'UG', name: 'Uganda' },
            { key: 'UA', name: 'Ukraine' },
            { key: 'AE', name: 'United Arab Emirates' },
            { key: 'GB', name: 'United Kingdom' },
            { key: 'US', name: 'United States', selected: true},
            { key: 'UM', name: 'United States Minor Outlying Islands' },
            { key: 'UY', name: 'Uruguay' },
            { key: 'UZ', name: 'Uzbekistan' },
            { key: 'VU', name: 'Vanuatu' },
            { key: 'VE', name: 'Venezuela' },
            { key: 'VN', name: 'Viet Nam' },
            { key: 'VG', name: 'Virgin Islands, British' },
            { key: 'VI', name: 'Virgin Islands, U.s.' },
            { key: 'WF', name: 'Wallis and Futuna' },
            { key: 'EH', name: 'Western Sahara' },
            { key: 'YE', name: 'Yemen' },
            { key: 'ZM', name: 'Zambia' },
            { key: 'ZW', name: 'Zimbabwe' }
        ],
        states: {
            US: [
                { key: 'AL', name: 'Alabama' },
                { key: 'AK', name: 'Alaska' },
                { key: 'AZ', name: 'Arizona' },
                { key: 'AR', name: 'Arkansas' },
                { key: 'CA', name: 'California' },
                { key: 'CO', name: 'Colorado' },
                { key: 'CT', name: 'Connecticut' },
                { key: 'DE', name: 'Delaware' },
                { key: 'DC', name: 'District Of Columbia' },
                { key: 'FL', name: 'Florida' },
                { key: 'GA', name: 'Georgia' },
                { key: 'HI', name: 'Hawaii' },
                { key: 'ID', name: 'Idaho' },
                { key: 'IL', name: 'Illinois' },
                { key: 'IN', name: 'Indiana' },
                { key: 'IA', name: 'Iowa' },
                { key: 'KS', name: 'Kansas' },
                { key: 'KY', name: 'Kentucky' },
                { key: 'LA', name: 'Louisiana' },
                { key: 'ME', name: 'Maine' },
                { key: 'MD', name: 'Maryland' },
                { key: 'MA', name: 'Massachusetts' },
                { key: 'MI', name: 'Michigan' },
                { key: 'MN', name: 'Minnesota' },
                { key: 'MS', name: 'Mississippi' },
                { key: 'MO', name: 'Missouri' },
                { key: 'MT', name: 'Montana' },
                { key: 'NE', name: 'Nebraska' },
                { key: 'NV', name: 'Nevada' },
                { key: 'NH', name: 'New Hampshire' },
                { key: 'NJ', name: 'New Jersey' },
                { key: 'NM', name: 'New Mexico' },
                { key: 'NY', name: 'New York' },
                { key: 'NC', name: 'North Carolina' },
                { key: 'ND', name: 'North Dakota' },
                { key: 'OH', name: 'Ohio' },
                { key: 'OK', name: 'Oklahoma' },
                { key: 'OR', name: 'Oregon' },
                { key: 'PA', name: 'Pennsylvania' },
                { key: 'RI', name: 'Rhode Island' },
                { key: 'SC', name: 'South Carolina' },
                { key: 'SD', name: 'South Dakota' },
                { key: 'TN', name: 'Tennessee' },
                { key: 'TX', name: 'Texas' },
                { key: 'UT', name: 'Utah' },
                { key: 'VT', name: 'Vermont' },
                { key: 'VA', name: 'Virginia' },
                { key: 'WA', name: 'Washington' },
                { key: 'WV', name: 'West Virginia' },
                { key: 'WI', name: 'Wisconsin' },
                { key: 'WY', name: 'Wyoming' }
            ]
        }
    }
}).call(this);
